# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_udsClient', [dirname(__file__)])
        except ImportError:
            import _udsClient
            return _udsClient
        if fp is not None:
            try:
                _mod = imp.load_module('_udsClient', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _udsClient = swig_import_helper()
    del swig_import_helper
else:
    import _udsClient
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


TRANSPORT_FRAME_SIZE = _udsClient.TRANSPORT_FRAME_SIZE
class UDS_protocolData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UDS_protocolData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UDS_protocolData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["udsProtocolData"] = _udsClient.UDS_protocolData_t_udsProtocolData_set
    __swig_getmethods__["udsProtocolData"] = _udsClient.UDS_protocolData_t_udsProtocolData_get
    if _newclass:udsProtocolData = _swig_property(_udsClient.UDS_protocolData_t_udsProtocolData_get, _udsClient.UDS_protocolData_t_udsProtocolData_set)
    __swig_setmethods__["udsProtocolByte"] = _udsClient.UDS_protocolData_t_udsProtocolByte_set
    __swig_getmethods__["udsProtocolByte"] = _udsClient.UDS_protocolData_t_udsProtocolByte_get
    if _newclass:udsProtocolByte = _swig_property(_udsClient.UDS_protocolData_t_udsProtocolByte_get, _udsClient.UDS_protocolData_t_udsProtocolByte_set)
    def __init__(self): 
        this = _udsClient.new_UDS_protocolData_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _udsClient.delete_UDS_protocolData_t
    __del__ = lambda self : None;
UDS_protocolData_t_swigregister = _udsClient.UDS_protocolData_t_swigregister
UDS_protocolData_t_swigregister(UDS_protocolData_t)

class nodeNetworkState_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, nodeNetworkState_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, nodeNetworkState_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["handleTaken"] = _udsClient.nodeNetworkState_t_handleTaken_set
    __swig_getmethods__["handleTaken"] = _udsClient.nodeNetworkState_t_handleTaken_get
    if _newclass:handleTaken = _swig_property(_udsClient.nodeNetworkState_t_handleTaken_get, _udsClient.nodeNetworkState_t_handleTaken_set)
    __swig_setmethods__["blockSize"] = _udsClient.nodeNetworkState_t_blockSize_set
    __swig_getmethods__["blockSize"] = _udsClient.nodeNetworkState_t_blockSize_get
    if _newclass:blockSize = _swig_property(_udsClient.nodeNetworkState_t_blockSize_get, _udsClient.nodeNetworkState_t_blockSize_set)
    __swig_setmethods__["STmin"] = _udsClient.nodeNetworkState_t_STmin_set
    __swig_getmethods__["STmin"] = _udsClient.nodeNetworkState_t_STmin_get
    if _newclass:STmin = _swig_property(_udsClient.nodeNetworkState_t_STmin_get, _udsClient.nodeNetworkState_t_STmin_set)
    __swig_setmethods__["busNumber"] = _udsClient.nodeNetworkState_t_busNumber_set
    __swig_getmethods__["busNumber"] = _udsClient.nodeNetworkState_t_busNumber_get
    if _newclass:busNumber = _swig_property(_udsClient.nodeNetworkState_t_busNumber_get, _udsClient.nodeNetworkState_t_busNumber_set)
    __swig_setmethods__["requestID"] = _udsClient.nodeNetworkState_t_requestID_set
    __swig_getmethods__["requestID"] = _udsClient.nodeNetworkState_t_requestID_get
    if _newclass:requestID = _swig_property(_udsClient.nodeNetworkState_t_requestID_get, _udsClient.nodeNetworkState_t_requestID_set)
    __swig_setmethods__["responseID"] = _udsClient.nodeNetworkState_t_responseID_set
    __swig_getmethods__["responseID"] = _udsClient.nodeNetworkState_t_responseID_get
    if _newclass:responseID = _swig_property(_udsClient.nodeNetworkState_t_responseID_get, _udsClient.nodeNetworkState_t_responseID_set)
    __swig_setmethods__["driverTimeout"] = _udsClient.nodeNetworkState_t_driverTimeout_set
    __swig_getmethods__["driverTimeout"] = _udsClient.nodeNetworkState_t_driverTimeout_get
    if _newclass:driverTimeout = _swig_property(_udsClient.nodeNetworkState_t_driverTimeout_get, _udsClient.nodeNetworkState_t_driverTimeout_set)
    __swig_setmethods__["remoteAddress"] = _udsClient.nodeNetworkState_t_remoteAddress_set
    __swig_getmethods__["remoteAddress"] = _udsClient.nodeNetworkState_t_remoteAddress_get
    if _newclass:remoteAddress = _swig_property(_udsClient.nodeNetworkState_t_remoteAddress_get, _udsClient.nodeNetworkState_t_remoteAddress_set)
    __swig_setmethods__["tpDataRequestPtr"] = _udsClient.nodeNetworkState_t_tpDataRequestPtr_set
    __swig_getmethods__["tpDataRequestPtr"] = _udsClient.nodeNetworkState_t_tpDataRequestPtr_get
    if _newclass:tpDataRequestPtr = _swig_property(_udsClient.nodeNetworkState_t_tpDataRequestPtr_get, _udsClient.nodeNetworkState_t_tpDataRequestPtr_set)
    __swig_setmethods__["tpDataIndicationPtr"] = _udsClient.nodeNetworkState_t_tpDataIndicationPtr_set
    __swig_getmethods__["tpDataIndicationPtr"] = _udsClient.nodeNetworkState_t_tpDataIndicationPtr_get
    if _newclass:tpDataIndicationPtr = _swig_property(_udsClient.nodeNetworkState_t_tpDataIndicationPtr_get, _udsClient.nodeNetworkState_t_tpDataIndicationPtr_set)
    def __init__(self): 
        this = _udsClient.new_nodeNetworkState_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _udsClient.delete_nodeNetworkState_t
    __del__ = lambda self : None;
nodeNetworkState_t_swigregister = _udsClient.nodeNetworkState_t_swigregister
nodeNetworkState_t_swigregister(nodeNetworkState_t)


def tpNetInitHandle():
  return _udsClient.tpNetInitHandle()
tpNetInitHandle = _udsClient.tpNetInitHandle

def tpNetFreeHandle(*args):
  return _udsClient.tpNetFreeHandle(*args)
tpNetFreeHandle = _udsClient.tpNetFreeHandle

def tpNetSetTimeout(*args):
  return _udsClient.tpNetSetTimeout(*args)
tpNetSetTimeout = _udsClient.tpNetSetTimeout

def tpNetSetMessageID(*args):
  return _udsClient.tpNetSetMessageID(*args)
tpNetSetMessageID = _udsClient.tpNetSetMessageID

def caNetGetHandle(*args):
  return _udsClient.caNetGetHandle(*args)
caNetGetHandle = _udsClient.caNetGetHandle

def liNetGetHandle(*args):
  return _udsClient.liNetGetHandle(*args)
liNetGetHandle = _udsClient.liNetGetHandle

def new_uint8Array(*args):
  return _udsClient.new_uint8Array(*args)
new_uint8Array = _udsClient.new_uint8Array

def delete_uint8Array(*args):
  return _udsClient.delete_uint8Array(*args)
delete_uint8Array = _udsClient.delete_uint8Array

def uint8Array_getitem(*args):
  return _udsClient.uint8Array_getitem(*args)
uint8Array_getitem = _udsClient.uint8Array_getitem

def uint8Array_setitem(*args):
  return _udsClient.uint8Array_setitem(*args)
uint8Array_setitem = _udsClient.uint8Array_setitem

def new_uint8p():
  return _udsClient.new_uint8p()
new_uint8p = _udsClient.new_uint8p

def copy_uint8p(*args):
  return _udsClient.copy_uint8p(*args)
copy_uint8p = _udsClient.copy_uint8p

def delete_uint8p(*args):
  return _udsClient.delete_uint8p(*args)
delete_uint8p = _udsClient.delete_uint8p

def uint8p_assign(*args):
  return _udsClient.uint8p_assign(*args)
uint8p_assign = _udsClient.uint8p_assign

def uint8p_value(*args):
  return _udsClient.uint8p_value(*args)
uint8p_value = _udsClient.uint8p_value

def new_uint16Array(*args):
  return _udsClient.new_uint16Array(*args)
new_uint16Array = _udsClient.new_uint16Array

def delete_uint16Array(*args):
  return _udsClient.delete_uint16Array(*args)
delete_uint16Array = _udsClient.delete_uint16Array

def uint16Array_getitem(*args):
  return _udsClient.uint16Array_getitem(*args)
uint16Array_getitem = _udsClient.uint16Array_getitem

def uint16Array_setitem(*args):
  return _udsClient.uint16Array_setitem(*args)
uint16Array_setitem = _udsClient.uint16Array_setitem

def new_uint16p():
  return _udsClient.new_uint16p()
new_uint16p = _udsClient.new_uint16p

def copy_uint16p(*args):
  return _udsClient.copy_uint16p(*args)
copy_uint16p = _udsClient.copy_uint16p

def delete_uint16p(*args):
  return _udsClient.delete_uint16p(*args)
delete_uint16p = _udsClient.delete_uint16p

def uint16p_assign(*args):
  return _udsClient.uint16p_assign(*args)
uint16p_assign = _udsClient.uint16p_assign

def uint16p_value(*args):
  return _udsClient.uint16p_value(*args)
uint16p_value = _udsClient.uint16p_value

def new_uint32Array(*args):
  return _udsClient.new_uint32Array(*args)
new_uint32Array = _udsClient.new_uint32Array

def delete_uint32Array(*args):
  return _udsClient.delete_uint32Array(*args)
delete_uint32Array = _udsClient.delete_uint32Array

def uint32Array_getitem(*args):
  return _udsClient.uint32Array_getitem(*args)
uint32Array_getitem = _udsClient.uint32Array_getitem

def uint32Array_setitem(*args):
  return _udsClient.uint32Array_setitem(*args)
uint32Array_setitem = _udsClient.uint32Array_setitem

def new_uint32p():
  return _udsClient.new_uint32p()
new_uint32p = _udsClient.new_uint32p

def copy_uint32p(*args):
  return _udsClient.copy_uint32p(*args)
copy_uint32p = _udsClient.copy_uint32p

def delete_uint32p(*args):
  return _udsClient.delete_uint32p(*args)
delete_uint32p = _udsClient.delete_uint32p

def uint32p_assign(*args):
  return _udsClient.uint32p_assign(*args)
uint32p_assign = _udsClient.uint32p_assign

def uint32p_value(*args):
  return _udsClient.uint32p_value(*args)
uint32p_value = _udsClient.uint32p_value

def caNetRegister(*args):
  return _udsClient.caNetRegister(*args)
caNetRegister = _udsClient.caNetRegister

def liNetRegister(*args):
  return _udsClient.liNetRegister(*args)
liNetRegister = _udsClient.liNetRegister

def udsVtpRegister(*args):
  return _udsClient.udsVtpRegister(*args)
udsVtpRegister = _udsClient.udsVtpRegister

def udsVtpGetHandle(*args):
  return _udsClient.udsVtpGetHandle(*args)
udsVtpGetHandle = _udsClient.udsVtpGetHandle
SUPPRESS_POS_RSP_MSG_IND_BIT = _udsClient.SUPPRESS_POS_RSP_MSG_IND_BIT
NET_OK = _udsClient.NET_OK
requestCorrectlyReceived_ResponsePending = _udsClient.requestCorrectlyReceived_ResponsePending
DiagnosticSessionControlSID = _udsClient.DiagnosticSessionControlSID
ECUResetSID = _udsClient.ECUResetSID
ClearDiagnosticInformationSID = _udsClient.ClearDiagnosticInformationSID
ReadDTCInformationSID = _udsClient.ReadDTCInformationSID
ReadDataByIdentifierSID = _udsClient.ReadDataByIdentifierSID
ReadMemoryByAddressSID = _udsClient.ReadMemoryByAddressSID
ReadScalingDataByIdentifierSID = _udsClient.ReadScalingDataByIdentifierSID
SecurityAccessSID = _udsClient.SecurityAccessSID
CommunicationControlSID = _udsClient.CommunicationControlSID
ReadDataByPeriodicIdentifierSID = _udsClient.ReadDataByPeriodicIdentifierSID
DynamicallyDefineDataIdentifierSID = _udsClient.DynamicallyDefineDataIdentifierSID
WriteDataByIdentifierSID = _udsClient.WriteDataByIdentifierSID
InputOutputControlByIdentifierSID = _udsClient.InputOutputControlByIdentifierSID
RoutineControlSID = _udsClient.RoutineControlSID
RequestDownloadSID = _udsClient.RequestDownloadSID
RequestUploadSID = _udsClient.RequestUploadSID
TransferDataSID = _udsClient.TransferDataSID
RequestTransferExitSID = _udsClient.RequestTransferExitSID
WriteMemoryByAddressSID = _udsClient.WriteMemoryByAddressSID
TesterPresentSID = _udsClient.TesterPresentSID
NegativeResponseSID = _udsClient.NegativeResponseSID
AccessTimingParameterSID = _udsClient.AccessTimingParameterSID
SecuredDataTransmissionSID = _udsClient.SecuredDataTransmissionSID
ControlDTCSettingSID = _udsClient.ControlDTCSettingSID
ResponseOnEventSID = _udsClient.ResponseOnEventSID
LinkControlSID = _udsClient.LinkControlSID
defaultSession = _udsClient.defaultSession
programmingSession = _udsClient.programmingSession
extendedDiagnosticSession = _udsClient.extendedDiagnosticSession
safetySystemDiagnosticSession = _udsClient.safetySystemDiagnosticSession
hardReset = _udsClient.hardReset
keyOffOnReset = _udsClient.keyOffOnReset
softReset = _udsClient.softReset
enableRapidPowerShutDown = _udsClient.enableRapidPowerShutDown
disableRapidPowerShutDown = _udsClient.disableRapidPowerShutDown
returnControlToECU = _udsClient.returnControlToECU
resetToDefault = _udsClient.resetToDefault
freezeCurrentState = _udsClient.freezeCurrentState
shortTermAdjustment = _udsClient.shortTermAdjustment
startRoutine = _udsClient.startRoutine
stopRoutine = _udsClient.stopRoutine
requestRoutineResults = _udsClient.requestRoutineResults
reportNumberOfDTCByStatusMaskSF = _udsClient.reportNumberOfDTCByStatusMaskSF
reportDTCByStatusMaskSF = _udsClient.reportDTCByStatusMaskSF
reportMirrorMemoryDTCByStatusMaskSF = _udsClient.reportMirrorMemoryDTCByStatusMaskSF
reportNumberOfMirrorMemoryDTCByStatusMaskSF = _udsClient.reportNumberOfMirrorMemoryDTCByStatusMaskSF
reportNumberOfEmissionsRelatedOBDDTCByStatusMaskSF = _udsClient.reportNumberOfEmissionsRelatedOBDDTCByStatusMaskSF
reportEmissionsRelatedOBDDTCByStatusMaskSF = _udsClient.reportEmissionsRelatedOBDDTCByStatusMaskSF
reportDTCSnapshotIdentificationSF = _udsClient.reportDTCSnapshotIdentificationSF
reportDTCSnapshotRecordByDTCNumberSF = _udsClient.reportDTCSnapshotRecordByDTCNumberSF
reportDTCSnapshotRecordByRecordNumberSF = _udsClient.reportDTCSnapshotRecordByRecordNumberSF
reportDTCExtendedDataRecordByDTCNumberSF = _udsClient.reportDTCExtendedDataRecordByDTCNumberSF
reportMirrorMemoryDTCExtendedDataRecordByDTCNumberSF = _udsClient.reportMirrorMemoryDTCExtendedDataRecordByDTCNumberSF
reportNumberOfDTCBySeverityMaskRecordSF = _udsClient.reportNumberOfDTCBySeverityMaskRecordSF
reportDTCBySeverityMaskRecordSF = _udsClient.reportDTCBySeverityMaskRecordSF
reportSeverityInformationOfDTCSF = _udsClient.reportSeverityInformationOfDTCSF
reportSupportedDTCSF = _udsClient.reportSupportedDTCSF
reportFirstTestFailedDTCSF = _udsClient.reportFirstTestFailedDTCSF
reportFirstConfirmedDTCSF = _udsClient.reportFirstConfirmedDTCSF
reportMostRecentTestFailedDTCSF = _udsClient.reportMostRecentTestFailedDTCSF
reportMostRecentConfirmedDTCSF = _udsClient.reportMostRecentConfirmedDTCSF
reportDTCFaultDetectionCounterSF = _udsClient.reportDTCFaultDetectionCounterSF
reportDTCWithPermanentStatusSF = _udsClient.reportDTCWithPermanentStatusSF
UDS_OK = _udsClient.UDS_OK
UDS_NEG_RESPONSE = _udsClient.UDS_NEG_RESPONSE
UDS_SID_MISMATCH = _udsClient.UDS_SID_MISMATCH
UDS_SUB_FUNC_MISMATCH = _udsClient.UDS_SUB_FUNC_MISMATCH
UDS_INVALID_PARAMETERS = _udsClient.UDS_INVALID_PARAMETERS
UDS_INVALID_SUBFUNCTION = _udsClient.UDS_INVALID_SUBFUNCTION
UDS_ALREADY_IN_SA = _udsClient.UDS_ALREADY_IN_SA
UDS_INVALID_TRANSPORT = _udsClient.UDS_INVALID_TRANSPORT
UDS_HARDWARE_BUSY = _udsClient.UDS_HARDWARE_BUSY
UDS_RESP_PENDING_TIMEOUT = _udsClient.UDS_RESP_PENDING_TIMEOUT
UDS_LAST_ERROR = _udsClient.UDS_LAST_ERROR
UDS_ZERO_LENGTH = _udsClient.UDS_ZERO_LENGTH
NO_COMPRESSION_AND_NO_ENCRYPTION = _udsClient.NO_COMPRESSION_AND_NO_ENCRYPTION
compressionNone = _udsClient.compressionNone
compressionLevel1 = _udsClient.compressionLevel1
compressionLevel2 = _udsClient.compressionLevel2
compressionLevel3 = _udsClient.compressionLevel3
encryptingNone = _udsClient.encryptingNone
encryptingLevel1 = _udsClient.encryptingLevel1
encryptingLevel2 = _udsClient.encryptingLevel2
encryptingLevel3 = _udsClient.encryptingLevel3
memorySizeOffset = _udsClient.memorySizeOffset
memorySizeMask = _udsClient.memorySizeMask
memoryAddressOffset = _udsClient.memoryAddressOffset
memoryAddressMask = _udsClient.memoryAddressMask
class DTCMaskRecord_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DTCMaskRecord_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DTCMaskRecord_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DTCHighByte"] = _udsClient.DTCMaskRecord_t_DTCHighByte_set
    __swig_getmethods__["DTCHighByte"] = _udsClient.DTCMaskRecord_t_DTCHighByte_get
    if _newclass:DTCHighByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCHighByte_get, _udsClient.DTCMaskRecord_t_DTCHighByte_set)
    __swig_setmethods__["DTCMiddleByte"] = _udsClient.DTCMaskRecord_t_DTCMiddleByte_set
    __swig_getmethods__["DTCMiddleByte"] = _udsClient.DTCMaskRecord_t_DTCMiddleByte_get
    if _newclass:DTCMiddleByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCMiddleByte_get, _udsClient.DTCMaskRecord_t_DTCMiddleByte_set)
    __swig_setmethods__["DTCLowByte"] = _udsClient.DTCMaskRecord_t_DTCLowByte_set
    __swig_getmethods__["DTCLowByte"] = _udsClient.DTCMaskRecord_t_DTCLowByte_get
    if _newclass:DTCLowByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCLowByte_get, _udsClient.DTCMaskRecord_t_DTCLowByte_set)
    def __init__(self): 
        this = _udsClient.new_DTCMaskRecord_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _udsClient.delete_DTCMaskRecord_t
    __del__ = lambda self : None;
DTCMaskRecord_t_swigregister = _udsClient.DTCMaskRecord_t_swigregister
DTCMaskRecord_t_swigregister(DTCMaskRecord_t)

class DTC_parameter_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DTC_parameter_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DTC_parameter_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sub_function"] = _udsClient.DTC_parameter_t_sub_function_set
    __swig_getmethods__["sub_function"] = _udsClient.DTC_parameter_t_sub_function_get
    if _newclass:sub_function = _swig_property(_udsClient.DTC_parameter_t_sub_function_get, _udsClient.DTC_parameter_t_sub_function_set)
    __swig_setmethods__["DTCMaskRecord"] = _udsClient.DTC_parameter_t_DTCMaskRecord_set
    __swig_getmethods__["DTCMaskRecord"] = _udsClient.DTC_parameter_t_DTCMaskRecord_get
    if _newclass:DTCMaskRecord = _swig_property(_udsClient.DTC_parameter_t_DTCMaskRecord_get, _udsClient.DTC_parameter_t_DTCMaskRecord_set)
    __swig_setmethods__["DTCSnapshotRecordNumber"] = _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_set
    __swig_getmethods__["DTCSnapshotRecordNumber"] = _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_get
    if _newclass:DTCSnapshotRecordNumber = _swig_property(_udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_get, _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_set)
    __swig_setmethods__["DTCExtendedDataRecordNumber"] = _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_set
    __swig_getmethods__["DTCExtendedDataRecordNumber"] = _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_get
    if _newclass:DTCExtendedDataRecordNumber = _swig_property(_udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_get, _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_set)
    __swig_setmethods__["DTCSeverityMask"] = _udsClient.DTC_parameter_t_DTCSeverityMask_set
    __swig_getmethods__["DTCSeverityMask"] = _udsClient.DTC_parameter_t_DTCSeverityMask_get
    if _newclass:DTCSeverityMask = _swig_property(_udsClient.DTC_parameter_t_DTCSeverityMask_get, _udsClient.DTC_parameter_t_DTCSeverityMask_set)
    __swig_setmethods__["DTCStatusMask"] = _udsClient.DTC_parameter_t_DTCStatusMask_set
    __swig_getmethods__["DTCStatusMask"] = _udsClient.DTC_parameter_t_DTCStatusMask_get
    if _newclass:DTCStatusMask = _swig_property(_udsClient.DTC_parameter_t_DTCStatusMask_get, _udsClient.DTC_parameter_t_DTCStatusMask_set)
    def __init__(self): 
        this = _udsClient.new_DTC_parameter_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _udsClient.delete_DTC_parameter_t
    __del__ = lambda self : None;
DTC_parameter_t_swigregister = _udsClient.DTC_parameter_t_swigregister
DTC_parameter_t_swigregister(DTC_parameter_t)


def udsDiagnosticSessionControl(*args):
  return _udsClient.udsDiagnosticSessionControl(*args)
udsDiagnosticSessionControl = _udsClient.udsDiagnosticSessionControl

def udsECUReset(*args):
  return _udsClient.udsECUReset(*args)
udsECUReset = _udsClient.udsECUReset

def udsClearDiagnosticInformation(*args):
  return _udsClient.udsClearDiagnosticInformation(*args)
udsClearDiagnosticInformation = _udsClient.udsClearDiagnosticInformation

def udsReadDTCInformation(*args):
  return _udsClient.udsReadDTCInformation(*args)
udsReadDTCInformation = _udsClient.udsReadDTCInformation

def udsReadDataByIdentifier(*args):
  return _udsClient.udsReadDataByIdentifier(*args)
udsReadDataByIdentifier = _udsClient.udsReadDataByIdentifier

def udsReadMemoryByAddress(*args):
  return _udsClient.udsReadMemoryByAddress(*args)
udsReadMemoryByAddress = _udsClient.udsReadMemoryByAddress

def udsSecurityAccessRequestSeed(*args):
  return _udsClient.udsSecurityAccessRequestSeed(*args)
udsSecurityAccessRequestSeed = _udsClient.udsSecurityAccessRequestSeed

def udsSecurityAccessSendKey(*args):
  return _udsClient.udsSecurityAccessSendKey(*args)
udsSecurityAccessSendKey = _udsClient.udsSecurityAccessSendKey

def udsCommunicationControl(*args):
  return _udsClient.udsCommunicationControl(*args)
udsCommunicationControl = _udsClient.udsCommunicationControl

def udsWriteDataByIdentifier(*args):
  return _udsClient.udsWriteDataByIdentifier(*args)
udsWriteDataByIdentifier = _udsClient.udsWriteDataByIdentifier

def udsInputOutputControlByIdentifier(*args):
  return _udsClient.udsInputOutputControlByIdentifier(*args)
udsInputOutputControlByIdentifier = _udsClient.udsInputOutputControlByIdentifier

def udsRoutineControl(*args):
  return _udsClient.udsRoutineControl(*args)
udsRoutineControl = _udsClient.udsRoutineControl

def udsRequestDownload(*args):
  return _udsClient.udsRequestDownload(*args)
udsRequestDownload = _udsClient.udsRequestDownload

def udsRequestUpload(*args):
  return _udsClient.udsRequestUpload(*args)
udsRequestUpload = _udsClient.udsRequestUpload

def udsTransferData(*args):
  return _udsClient.udsTransferData(*args)
udsTransferData = _udsClient.udsTransferData

def udsRequestTransferExit(*args):
  return _udsClient.udsRequestTransferExit(*args)
udsRequestTransferExit = _udsClient.udsRequestTransferExit

def udsTesterPresent(*args):
  return _udsClient.udsTesterPresent(*args)
udsTesterPresent = _udsClient.udsTesterPresent

def udsWriteMemoryByAddress(*args):
  return _udsClient.udsWriteMemoryByAddress(*args)
udsWriteMemoryByAddress = _udsClient.udsWriteMemoryByAddress

def udsControlDTCSetting(*args):
  return _udsClient.udsControlDTCSetting(*args)
udsControlDTCSetting = _udsClient.udsControlDTCSetting
# This file is compatible with both classic and new-style classes.


