# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_udsClient', [dirname(__file__)])
        except ImportError:
            import _udsClient
            return _udsClient
        if fp is not None:
            try:
                _mod = imp.load_module('_udsClient', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _udsClient = swig_import_helper()
    del swig_import_helper
else:
    import _udsClient
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_udsClient.TRANSPORT_FRAME_SIZE_swigconstant(_udsClient)
TRANSPORT_FRAME_SIZE = _udsClient.TRANSPORT_FRAME_SIZE
class UDS_protocolData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UDS_protocolData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UDS_protocolData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["udsProtocolData"] = _udsClient.UDS_protocolData_t_udsProtocolData_set
    __swig_getmethods__["udsProtocolData"] = _udsClient.UDS_protocolData_t_udsProtocolData_get
    if _newclass:
        udsProtocolData = _swig_property(_udsClient.UDS_protocolData_t_udsProtocolData_get, _udsClient.UDS_protocolData_t_udsProtocolData_set)
    __swig_setmethods__["udsProtocolByte"] = _udsClient.UDS_protocolData_t_udsProtocolByte_set
    __swig_getmethods__["udsProtocolByte"] = _udsClient.UDS_protocolData_t_udsProtocolByte_get
    if _newclass:
        udsProtocolByte = _swig_property(_udsClient.UDS_protocolData_t_udsProtocolByte_get, _udsClient.UDS_protocolData_t_udsProtocolByte_set)

    def __init__(self):
        this = _udsClient.new_UDS_protocolData_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _udsClient.delete_UDS_protocolData_t
    __del__ = lambda self: None
UDS_protocolData_t_swigregister = _udsClient.UDS_protocolData_t_swigregister
UDS_protocolData_t_swigregister(UDS_protocolData_t)

class nodeNetworkState_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, nodeNetworkState_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, nodeNetworkState_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["handleTaken"] = _udsClient.nodeNetworkState_t_handleTaken_set
    __swig_getmethods__["handleTaken"] = _udsClient.nodeNetworkState_t_handleTaken_get
    if _newclass:
        handleTaken = _swig_property(_udsClient.nodeNetworkState_t_handleTaken_get, _udsClient.nodeNetworkState_t_handleTaken_set)
    __swig_setmethods__["blockSize"] = _udsClient.nodeNetworkState_t_blockSize_set
    __swig_getmethods__["blockSize"] = _udsClient.nodeNetworkState_t_blockSize_get
    if _newclass:
        blockSize = _swig_property(_udsClient.nodeNetworkState_t_blockSize_get, _udsClient.nodeNetworkState_t_blockSize_set)
    __swig_setmethods__["STmin"] = _udsClient.nodeNetworkState_t_STmin_set
    __swig_getmethods__["STmin"] = _udsClient.nodeNetworkState_t_STmin_get
    if _newclass:
        STmin = _swig_property(_udsClient.nodeNetworkState_t_STmin_get, _udsClient.nodeNetworkState_t_STmin_set)
    __swig_setmethods__["busNumber"] = _udsClient.nodeNetworkState_t_busNumber_set
    __swig_getmethods__["busNumber"] = _udsClient.nodeNetworkState_t_busNumber_get
    if _newclass:
        busNumber = _swig_property(_udsClient.nodeNetworkState_t_busNumber_get, _udsClient.nodeNetworkState_t_busNumber_set)
    __swig_setmethods__["requestID"] = _udsClient.nodeNetworkState_t_requestID_set
    __swig_getmethods__["requestID"] = _udsClient.nodeNetworkState_t_requestID_get
    if _newclass:
        requestID = _swig_property(_udsClient.nodeNetworkState_t_requestID_get, _udsClient.nodeNetworkState_t_requestID_set)
    __swig_setmethods__["responseID"] = _udsClient.nodeNetworkState_t_responseID_set
    __swig_getmethods__["responseID"] = _udsClient.nodeNetworkState_t_responseID_get
    if _newclass:
        responseID = _swig_property(_udsClient.nodeNetworkState_t_responseID_get, _udsClient.nodeNetworkState_t_responseID_set)
    __swig_setmethods__["driverTimeout"] = _udsClient.nodeNetworkState_t_driverTimeout_set
    __swig_getmethods__["driverTimeout"] = _udsClient.nodeNetworkState_t_driverTimeout_get
    if _newclass:
        driverTimeout = _swig_property(_udsClient.nodeNetworkState_t_driverTimeout_get, _udsClient.nodeNetworkState_t_driverTimeout_set)
    __swig_setmethods__["remoteAddress"] = _udsClient.nodeNetworkState_t_remoteAddress_set
    __swig_getmethods__["remoteAddress"] = _udsClient.nodeNetworkState_t_remoteAddress_get
    if _newclass:
        remoteAddress = _swig_property(_udsClient.nodeNetworkState_t_remoteAddress_get, _udsClient.nodeNetworkState_t_remoteAddress_set)
    __swig_setmethods__["tpDataRequestPtr"] = _udsClient.nodeNetworkState_t_tpDataRequestPtr_set
    __swig_getmethods__["tpDataRequestPtr"] = _udsClient.nodeNetworkState_t_tpDataRequestPtr_get
    if _newclass:
        tpDataRequestPtr = _swig_property(_udsClient.nodeNetworkState_t_tpDataRequestPtr_get, _udsClient.nodeNetworkState_t_tpDataRequestPtr_set)
    __swig_setmethods__["tpDataIndicationPtr"] = _udsClient.nodeNetworkState_t_tpDataIndicationPtr_set
    __swig_getmethods__["tpDataIndicationPtr"] = _udsClient.nodeNetworkState_t_tpDataIndicationPtr_get
    if _newclass:
        tpDataIndicationPtr = _swig_property(_udsClient.nodeNetworkState_t_tpDataIndicationPtr_get, _udsClient.nodeNetworkState_t_tpDataIndicationPtr_set)

    def __init__(self):
        this = _udsClient.new_nodeNetworkState_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _udsClient.delete_nodeNetworkState_t
    __del__ = lambda self: None
nodeNetworkState_t_swigregister = _udsClient.nodeNetworkState_t_swigregister
nodeNetworkState_t_swigregister(nodeNetworkState_t)


def tpNetInitHandle():
    return _udsClient.tpNetInitHandle()
tpNetInitHandle = _udsClient.tpNetInitHandle

def tpNetFreeHandle(canHandle):
    return _udsClient.tpNetFreeHandle(canHandle)
tpNetFreeHandle = _udsClient.tpNetFreeHandle

def tpNetSetTimeout(canHandle, newTimeout):
    return _udsClient.tpNetSetTimeout(canHandle, newTimeout)
tpNetSetTimeout = _udsClient.tpNetSetTimeout

def tpNetSetMessageID(canHandle, newRequestID, newResponseID):
    return _udsClient.tpNetSetMessageID(canHandle, newRequestID, newResponseID)
tpNetSetMessageID = _udsClient.tpNetSetMessageID

def caNetGetHandle(nodeNum):
    return _udsClient.caNetGetHandle(nodeNum)
caNetGetHandle = _udsClient.caNetGetHandle

def liNetGetHandle(nodeNum):
    return _udsClient.liNetGetHandle(nodeNum)
liNetGetHandle = _udsClient.liNetGetHandle

def new_uint8Array(nelements):
    return _udsClient.new_uint8Array(nelements)
new_uint8Array = _udsClient.new_uint8Array

def delete_uint8Array(ary):
    return _udsClient.delete_uint8Array(ary)
delete_uint8Array = _udsClient.delete_uint8Array

def uint8Array_getitem(ary, index):
    return _udsClient.uint8Array_getitem(ary, index)
uint8Array_getitem = _udsClient.uint8Array_getitem

def uint8Array_setitem(ary, index, value):
    return _udsClient.uint8Array_setitem(ary, index, value)
uint8Array_setitem = _udsClient.uint8Array_setitem

def new_uint8p():
    return _udsClient.new_uint8p()
new_uint8p = _udsClient.new_uint8p

def copy_uint8p(value):
    return _udsClient.copy_uint8p(value)
copy_uint8p = _udsClient.copy_uint8p

def delete_uint8p(obj):
    return _udsClient.delete_uint8p(obj)
delete_uint8p = _udsClient.delete_uint8p

def uint8p_assign(obj, value):
    return _udsClient.uint8p_assign(obj, value)
uint8p_assign = _udsClient.uint8p_assign

def uint8p_value(obj):
    return _udsClient.uint8p_value(obj)
uint8p_value = _udsClient.uint8p_value

def new_uint16Array(nelements):
    return _udsClient.new_uint16Array(nelements)
new_uint16Array = _udsClient.new_uint16Array

def delete_uint16Array(ary):
    return _udsClient.delete_uint16Array(ary)
delete_uint16Array = _udsClient.delete_uint16Array

def uint16Array_getitem(ary, index):
    return _udsClient.uint16Array_getitem(ary, index)
uint16Array_getitem = _udsClient.uint16Array_getitem

def uint16Array_setitem(ary, index, value):
    return _udsClient.uint16Array_setitem(ary, index, value)
uint16Array_setitem = _udsClient.uint16Array_setitem

def new_uint16p():
    return _udsClient.new_uint16p()
new_uint16p = _udsClient.new_uint16p

def copy_uint16p(value):
    return _udsClient.copy_uint16p(value)
copy_uint16p = _udsClient.copy_uint16p

def delete_uint16p(obj):
    return _udsClient.delete_uint16p(obj)
delete_uint16p = _udsClient.delete_uint16p

def uint16p_assign(obj, value):
    return _udsClient.uint16p_assign(obj, value)
uint16p_assign = _udsClient.uint16p_assign

def uint16p_value(obj):
    return _udsClient.uint16p_value(obj)
uint16p_value = _udsClient.uint16p_value

def new_uint32Array(nelements):
    return _udsClient.new_uint32Array(nelements)
new_uint32Array = _udsClient.new_uint32Array

def delete_uint32Array(ary):
    return _udsClient.delete_uint32Array(ary)
delete_uint32Array = _udsClient.delete_uint32Array

def uint32Array_getitem(ary, index):
    return _udsClient.uint32Array_getitem(ary, index)
uint32Array_getitem = _udsClient.uint32Array_getitem

def uint32Array_setitem(ary, index, value):
    return _udsClient.uint32Array_setitem(ary, index, value)
uint32Array_setitem = _udsClient.uint32Array_setitem

def new_uint32p():
    return _udsClient.new_uint32p()
new_uint32p = _udsClient.new_uint32p

def copy_uint32p(value):
    return _udsClient.copy_uint32p(value)
copy_uint32p = _udsClient.copy_uint32p

def delete_uint32p(obj):
    return _udsClient.delete_uint32p(obj)
delete_uint32p = _udsClient.delete_uint32p

def uint32p_assign(obj, value):
    return _udsClient.uint32p_assign(obj, value)
uint32p_assign = _udsClient.uint32p_assign

def uint32p_value(obj):
    return _udsClient.uint32p_value(obj)
uint32p_value = _udsClient.uint32p_value

def caNetRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication, caNetClearRecQueue):
    return _udsClient.caNetRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication, caNetClearRecQueue)
caNetRegister = _udsClient.caNetRegister

def liNetRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication):
    return _udsClient.liNetRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication)
liNetRegister = _udsClient.liNetRegister

def udsVtpRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication):
    return _udsClient.udsVtpRegister(newTpGetNodeInfo, newTpDataRequest, newTpDataIndication)
udsVtpRegister = _udsClient.udsVtpRegister

def udsVtpGetHandle(nodeNum):
    return _udsClient.udsVtpGetHandle(nodeNum)
udsVtpGetHandle = _udsClient.udsVtpGetHandle

_udsClient.SUPPRESS_POS_RSP_MSG_IND_BIT_swigconstant(_udsClient)
SUPPRESS_POS_RSP_MSG_IND_BIT = _udsClient.SUPPRESS_POS_RSP_MSG_IND_BIT

_udsClient.NET_OK_swigconstant(_udsClient)
NET_OK = _udsClient.NET_OK

_udsClient.requestCorrectlyReceived_ResponsePending_swigconstant(_udsClient)
requestCorrectlyReceived_ResponsePending = _udsClient.requestCorrectlyReceived_ResponsePending

_udsClient.DiagnosticSessionControlSID_swigconstant(_udsClient)
DiagnosticSessionControlSID = _udsClient.DiagnosticSessionControlSID

_udsClient.ECUResetSID_swigconstant(_udsClient)
ECUResetSID = _udsClient.ECUResetSID

_udsClient.ClearDiagnosticInformationSID_swigconstant(_udsClient)
ClearDiagnosticInformationSID = _udsClient.ClearDiagnosticInformationSID

_udsClient.ReadDTCInformationSID_swigconstant(_udsClient)
ReadDTCInformationSID = _udsClient.ReadDTCInformationSID

_udsClient.ReadDataByIdentifierSID_swigconstant(_udsClient)
ReadDataByIdentifierSID = _udsClient.ReadDataByIdentifierSID

_udsClient.ReadMemoryByAddressSID_swigconstant(_udsClient)
ReadMemoryByAddressSID = _udsClient.ReadMemoryByAddressSID

_udsClient.ReadScalingDataByIdentifierSID_swigconstant(_udsClient)
ReadScalingDataByIdentifierSID = _udsClient.ReadScalingDataByIdentifierSID

_udsClient.SecurityAccessSID_swigconstant(_udsClient)
SecurityAccessSID = _udsClient.SecurityAccessSID

_udsClient.CommunicationControlSID_swigconstant(_udsClient)
CommunicationControlSID = _udsClient.CommunicationControlSID

_udsClient.ReadDataByPeriodicIdentifierSID_swigconstant(_udsClient)
ReadDataByPeriodicIdentifierSID = _udsClient.ReadDataByPeriodicIdentifierSID

_udsClient.DynamicallyDefineDataIdentifierSID_swigconstant(_udsClient)
DynamicallyDefineDataIdentifierSID = _udsClient.DynamicallyDefineDataIdentifierSID

_udsClient.WriteDataByIdentifierSID_swigconstant(_udsClient)
WriteDataByIdentifierSID = _udsClient.WriteDataByIdentifierSID

_udsClient.InputOutputControlByIdentifierSID_swigconstant(_udsClient)
InputOutputControlByIdentifierSID = _udsClient.InputOutputControlByIdentifierSID

_udsClient.RoutineControlSID_swigconstant(_udsClient)
RoutineControlSID = _udsClient.RoutineControlSID

_udsClient.RequestDownloadSID_swigconstant(_udsClient)
RequestDownloadSID = _udsClient.RequestDownloadSID

_udsClient.RequestUploadSID_swigconstant(_udsClient)
RequestUploadSID = _udsClient.RequestUploadSID

_udsClient.TransferDataSID_swigconstant(_udsClient)
TransferDataSID = _udsClient.TransferDataSID

_udsClient.RequestTransferExitSID_swigconstant(_udsClient)
RequestTransferExitSID = _udsClient.RequestTransferExitSID

_udsClient.WriteMemoryByAddressSID_swigconstant(_udsClient)
WriteMemoryByAddressSID = _udsClient.WriteMemoryByAddressSID

_udsClient.TesterPresentSID_swigconstant(_udsClient)
TesterPresentSID = _udsClient.TesterPresentSID

_udsClient.NegativeResponseSID_swigconstant(_udsClient)
NegativeResponseSID = _udsClient.NegativeResponseSID

_udsClient.AccessTimingParameterSID_swigconstant(_udsClient)
AccessTimingParameterSID = _udsClient.AccessTimingParameterSID

_udsClient.SecuredDataTransmissionSID_swigconstant(_udsClient)
SecuredDataTransmissionSID = _udsClient.SecuredDataTransmissionSID

_udsClient.ControlDTCSettingSID_swigconstant(_udsClient)
ControlDTCSettingSID = _udsClient.ControlDTCSettingSID

_udsClient.ResponseOnEventSID_swigconstant(_udsClient)
ResponseOnEventSID = _udsClient.ResponseOnEventSID

_udsClient.LinkControlSID_swigconstant(_udsClient)
LinkControlSID = _udsClient.LinkControlSID

_udsClient.defaultSession_swigconstant(_udsClient)
defaultSession = _udsClient.defaultSession

_udsClient.programmingSession_swigconstant(_udsClient)
programmingSession = _udsClient.programmingSession

_udsClient.extendedDiagnosticSession_swigconstant(_udsClient)
extendedDiagnosticSession = _udsClient.extendedDiagnosticSession

_udsClient.safetySystemDiagnosticSession_swigconstant(_udsClient)
safetySystemDiagnosticSession = _udsClient.safetySystemDiagnosticSession

_udsClient.hardReset_swigconstant(_udsClient)
hardReset = _udsClient.hardReset

_udsClient.keyOffOnReset_swigconstant(_udsClient)
keyOffOnReset = _udsClient.keyOffOnReset

_udsClient.softReset_swigconstant(_udsClient)
softReset = _udsClient.softReset

_udsClient.enableRapidPowerShutDown_swigconstant(_udsClient)
enableRapidPowerShutDown = _udsClient.enableRapidPowerShutDown

_udsClient.disableRapidPowerShutDown_swigconstant(_udsClient)
disableRapidPowerShutDown = _udsClient.disableRapidPowerShutDown

_udsClient.returnControlToECU_swigconstant(_udsClient)
returnControlToECU = _udsClient.returnControlToECU

_udsClient.resetToDefault_swigconstant(_udsClient)
resetToDefault = _udsClient.resetToDefault

_udsClient.freezeCurrentState_swigconstant(_udsClient)
freezeCurrentState = _udsClient.freezeCurrentState

_udsClient.shortTermAdjustment_swigconstant(_udsClient)
shortTermAdjustment = _udsClient.shortTermAdjustment

_udsClient.startRoutine_swigconstant(_udsClient)
startRoutine = _udsClient.startRoutine

_udsClient.stopRoutine_swigconstant(_udsClient)
stopRoutine = _udsClient.stopRoutine

_udsClient.requestRoutineResults_swigconstant(_udsClient)
requestRoutineResults = _udsClient.requestRoutineResults

_udsClient.reportNumberOfDTCByStatusMaskSF_swigconstant(_udsClient)
reportNumberOfDTCByStatusMaskSF = _udsClient.reportNumberOfDTCByStatusMaskSF

_udsClient.reportDTCByStatusMaskSF_swigconstant(_udsClient)
reportDTCByStatusMaskSF = _udsClient.reportDTCByStatusMaskSF

_udsClient.reportMirrorMemoryDTCByStatusMaskSF_swigconstant(_udsClient)
reportMirrorMemoryDTCByStatusMaskSF = _udsClient.reportMirrorMemoryDTCByStatusMaskSF

_udsClient.reportNumberOfMirrorMemoryDTCByStatusMaskSF_swigconstant(_udsClient)
reportNumberOfMirrorMemoryDTCByStatusMaskSF = _udsClient.reportNumberOfMirrorMemoryDTCByStatusMaskSF

_udsClient.reportNumberOfEmissionsRelatedOBDDTCByStatusMaskSF_swigconstant(_udsClient)
reportNumberOfEmissionsRelatedOBDDTCByStatusMaskSF = _udsClient.reportNumberOfEmissionsRelatedOBDDTCByStatusMaskSF

_udsClient.reportEmissionsRelatedOBDDTCByStatusMaskSF_swigconstant(_udsClient)
reportEmissionsRelatedOBDDTCByStatusMaskSF = _udsClient.reportEmissionsRelatedOBDDTCByStatusMaskSF

_udsClient.reportDTCSnapshotIdentificationSF_swigconstant(_udsClient)
reportDTCSnapshotIdentificationSF = _udsClient.reportDTCSnapshotIdentificationSF

_udsClient.reportDTCSnapshotRecordByDTCNumberSF_swigconstant(_udsClient)
reportDTCSnapshotRecordByDTCNumberSF = _udsClient.reportDTCSnapshotRecordByDTCNumberSF

_udsClient.reportDTCSnapshotRecordByRecordNumberSF_swigconstant(_udsClient)
reportDTCSnapshotRecordByRecordNumberSF = _udsClient.reportDTCSnapshotRecordByRecordNumberSF

_udsClient.reportDTCExtendedDataRecordByDTCNumberSF_swigconstant(_udsClient)
reportDTCExtendedDataRecordByDTCNumberSF = _udsClient.reportDTCExtendedDataRecordByDTCNumberSF

_udsClient.reportMirrorMemoryDTCExtendedDataRecordByDTCNumberSF_swigconstant(_udsClient)
reportMirrorMemoryDTCExtendedDataRecordByDTCNumberSF = _udsClient.reportMirrorMemoryDTCExtendedDataRecordByDTCNumberSF

_udsClient.reportNumberOfDTCBySeverityMaskRecordSF_swigconstant(_udsClient)
reportNumberOfDTCBySeverityMaskRecordSF = _udsClient.reportNumberOfDTCBySeverityMaskRecordSF

_udsClient.reportDTCBySeverityMaskRecordSF_swigconstant(_udsClient)
reportDTCBySeverityMaskRecordSF = _udsClient.reportDTCBySeverityMaskRecordSF

_udsClient.reportSeverityInformationOfDTCSF_swigconstant(_udsClient)
reportSeverityInformationOfDTCSF = _udsClient.reportSeverityInformationOfDTCSF

_udsClient.reportSupportedDTCSF_swigconstant(_udsClient)
reportSupportedDTCSF = _udsClient.reportSupportedDTCSF

_udsClient.reportFirstTestFailedDTCSF_swigconstant(_udsClient)
reportFirstTestFailedDTCSF = _udsClient.reportFirstTestFailedDTCSF

_udsClient.reportFirstConfirmedDTCSF_swigconstant(_udsClient)
reportFirstConfirmedDTCSF = _udsClient.reportFirstConfirmedDTCSF

_udsClient.reportMostRecentTestFailedDTCSF_swigconstant(_udsClient)
reportMostRecentTestFailedDTCSF = _udsClient.reportMostRecentTestFailedDTCSF

_udsClient.reportMostRecentConfirmedDTCSF_swigconstant(_udsClient)
reportMostRecentConfirmedDTCSF = _udsClient.reportMostRecentConfirmedDTCSF

_udsClient.reportDTCFaultDetectionCounterSF_swigconstant(_udsClient)
reportDTCFaultDetectionCounterSF = _udsClient.reportDTCFaultDetectionCounterSF

_udsClient.reportDTCWithPermanentStatusSF_swigconstant(_udsClient)
reportDTCWithPermanentStatusSF = _udsClient.reportDTCWithPermanentStatusSF

_udsClient.UDS_OK_swigconstant(_udsClient)
UDS_OK = _udsClient.UDS_OK

_udsClient.UDS_NEG_RESPONSE_swigconstant(_udsClient)
UDS_NEG_RESPONSE = _udsClient.UDS_NEG_RESPONSE

_udsClient.UDS_SID_MISMATCH_swigconstant(_udsClient)
UDS_SID_MISMATCH = _udsClient.UDS_SID_MISMATCH

_udsClient.UDS_SUB_FUNC_MISMATCH_swigconstant(_udsClient)
UDS_SUB_FUNC_MISMATCH = _udsClient.UDS_SUB_FUNC_MISMATCH

_udsClient.UDS_INVALID_PARAMETERS_swigconstant(_udsClient)
UDS_INVALID_PARAMETERS = _udsClient.UDS_INVALID_PARAMETERS

_udsClient.UDS_INVALID_SUBFUNCTION_swigconstant(_udsClient)
UDS_INVALID_SUBFUNCTION = _udsClient.UDS_INVALID_SUBFUNCTION

_udsClient.UDS_ALREADY_IN_SA_swigconstant(_udsClient)
UDS_ALREADY_IN_SA = _udsClient.UDS_ALREADY_IN_SA

_udsClient.UDS_INVALID_TRANSPORT_swigconstant(_udsClient)
UDS_INVALID_TRANSPORT = _udsClient.UDS_INVALID_TRANSPORT

_udsClient.UDS_HARDWARE_BUSY_swigconstant(_udsClient)
UDS_HARDWARE_BUSY = _udsClient.UDS_HARDWARE_BUSY

_udsClient.UDS_RESP_PENDING_TIMEOUT_swigconstant(_udsClient)
UDS_RESP_PENDING_TIMEOUT = _udsClient.UDS_RESP_PENDING_TIMEOUT

_udsClient.UDS_LAST_ERROR_swigconstant(_udsClient)
UDS_LAST_ERROR = _udsClient.UDS_LAST_ERROR

_udsClient.UDS_ZERO_LENGTH_swigconstant(_udsClient)
UDS_ZERO_LENGTH = _udsClient.UDS_ZERO_LENGTH

_udsClient.NO_COMPRESSION_AND_NO_ENCRYPTION_swigconstant(_udsClient)
NO_COMPRESSION_AND_NO_ENCRYPTION = _udsClient.NO_COMPRESSION_AND_NO_ENCRYPTION

_udsClient.compressionNone_swigconstant(_udsClient)
compressionNone = _udsClient.compressionNone

_udsClient.compressionLevel1_swigconstant(_udsClient)
compressionLevel1 = _udsClient.compressionLevel1

_udsClient.compressionLevel2_swigconstant(_udsClient)
compressionLevel2 = _udsClient.compressionLevel2

_udsClient.compressionLevel3_swigconstant(_udsClient)
compressionLevel3 = _udsClient.compressionLevel3

_udsClient.encryptingNone_swigconstant(_udsClient)
encryptingNone = _udsClient.encryptingNone

_udsClient.encryptingLevel1_swigconstant(_udsClient)
encryptingLevel1 = _udsClient.encryptingLevel1

_udsClient.encryptingLevel2_swigconstant(_udsClient)
encryptingLevel2 = _udsClient.encryptingLevel2

_udsClient.encryptingLevel3_swigconstant(_udsClient)
encryptingLevel3 = _udsClient.encryptingLevel3

_udsClient.memorySizeOffset_swigconstant(_udsClient)
memorySizeOffset = _udsClient.memorySizeOffset

_udsClient.memorySizeMask_swigconstant(_udsClient)
memorySizeMask = _udsClient.memorySizeMask

_udsClient.memoryAddressOffset_swigconstant(_udsClient)
memoryAddressOffset = _udsClient.memoryAddressOffset

_udsClient.memoryAddressMask_swigconstant(_udsClient)
memoryAddressMask = _udsClient.memoryAddressMask
class DTCMaskRecord_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DTCMaskRecord_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DTCMaskRecord_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DTCHighByte"] = _udsClient.DTCMaskRecord_t_DTCHighByte_set
    __swig_getmethods__["DTCHighByte"] = _udsClient.DTCMaskRecord_t_DTCHighByte_get
    if _newclass:
        DTCHighByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCHighByte_get, _udsClient.DTCMaskRecord_t_DTCHighByte_set)
    __swig_setmethods__["DTCMiddleByte"] = _udsClient.DTCMaskRecord_t_DTCMiddleByte_set
    __swig_getmethods__["DTCMiddleByte"] = _udsClient.DTCMaskRecord_t_DTCMiddleByte_get
    if _newclass:
        DTCMiddleByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCMiddleByte_get, _udsClient.DTCMaskRecord_t_DTCMiddleByte_set)
    __swig_setmethods__["DTCLowByte"] = _udsClient.DTCMaskRecord_t_DTCLowByte_set
    __swig_getmethods__["DTCLowByte"] = _udsClient.DTCMaskRecord_t_DTCLowByte_get
    if _newclass:
        DTCLowByte = _swig_property(_udsClient.DTCMaskRecord_t_DTCLowByte_get, _udsClient.DTCMaskRecord_t_DTCLowByte_set)

    def __init__(self):
        this = _udsClient.new_DTCMaskRecord_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _udsClient.delete_DTCMaskRecord_t
    __del__ = lambda self: None
DTCMaskRecord_t_swigregister = _udsClient.DTCMaskRecord_t_swigregister
DTCMaskRecord_t_swigregister(DTCMaskRecord_t)

class DTC_parameter_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DTC_parameter_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DTC_parameter_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sub_function"] = _udsClient.DTC_parameter_t_sub_function_set
    __swig_getmethods__["sub_function"] = _udsClient.DTC_parameter_t_sub_function_get
    if _newclass:
        sub_function = _swig_property(_udsClient.DTC_parameter_t_sub_function_get, _udsClient.DTC_parameter_t_sub_function_set)
    __swig_setmethods__["DTCMaskRecord"] = _udsClient.DTC_parameter_t_DTCMaskRecord_set
    __swig_getmethods__["DTCMaskRecord"] = _udsClient.DTC_parameter_t_DTCMaskRecord_get
    if _newclass:
        DTCMaskRecord = _swig_property(_udsClient.DTC_parameter_t_DTCMaskRecord_get, _udsClient.DTC_parameter_t_DTCMaskRecord_set)
    __swig_setmethods__["DTCSnapshotRecordNumber"] = _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_set
    __swig_getmethods__["DTCSnapshotRecordNumber"] = _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_get
    if _newclass:
        DTCSnapshotRecordNumber = _swig_property(_udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_get, _udsClient.DTC_parameter_t_DTCSnapshotRecordNumber_set)
    __swig_setmethods__["DTCExtendedDataRecordNumber"] = _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_set
    __swig_getmethods__["DTCExtendedDataRecordNumber"] = _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_get
    if _newclass:
        DTCExtendedDataRecordNumber = _swig_property(_udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_get, _udsClient.DTC_parameter_t_DTCExtendedDataRecordNumber_set)
    __swig_setmethods__["DTCSeverityMask"] = _udsClient.DTC_parameter_t_DTCSeverityMask_set
    __swig_getmethods__["DTCSeverityMask"] = _udsClient.DTC_parameter_t_DTCSeverityMask_get
    if _newclass:
        DTCSeverityMask = _swig_property(_udsClient.DTC_parameter_t_DTCSeverityMask_get, _udsClient.DTC_parameter_t_DTCSeverityMask_set)
    __swig_setmethods__["DTCStatusMask"] = _udsClient.DTC_parameter_t_DTCStatusMask_set
    __swig_getmethods__["DTCStatusMask"] = _udsClient.DTC_parameter_t_DTCStatusMask_get
    if _newclass:
        DTCStatusMask = _swig_property(_udsClient.DTC_parameter_t_DTCStatusMask_get, _udsClient.DTC_parameter_t_DTCStatusMask_set)

    def __init__(self):
        this = _udsClient.new_DTC_parameter_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _udsClient.delete_DTC_parameter_t
    __del__ = lambda self: None
DTC_parameter_t_swigregister = _udsClient.DTC_parameter_t_swigregister
DTC_parameter_t_swigregister(DTC_parameter_t)


def udsDiagnosticSessionControl(nHandle, diagnosticSessionType, responseRequired):
    return _udsClient.udsDiagnosticSessionControl(nHandle, diagnosticSessionType, responseRequired)
udsDiagnosticSessionControl = _udsClient.udsDiagnosticSessionControl

def udsECUReset(nHandle, resetType, powerDownTime, responseRequired):
    return _udsClient.udsECUReset(nHandle, resetType, powerDownTime, responseRequired)
udsECUReset = _udsClient.udsECUReset

def udsClearDiagnosticInformation(nHandle, groupOfDTC):
    return _udsClient.udsClearDiagnosticInformation(nHandle, groupOfDTC)
udsClearDiagnosticInformation = _udsClient.udsClearDiagnosticInformation

def udsReadDTCInformation(nHandle, bufferLength, retrievedData, actualLength, requestData):
    return _udsClient.udsReadDTCInformation(nHandle, bufferLength, retrievedData, actualLength, requestData)
udsReadDTCInformation = _udsClient.udsReadDTCInformation

def udsReadDataByIdentifier(nHandle, dataIdentifier, recordLength, dataRecord, actualLength):
    return _udsClient.udsReadDataByIdentifier(nHandle, dataIdentifier, recordLength, dataRecord, actualLength)
udsReadDataByIdentifier = _udsClient.udsReadDataByIdentifier

def udsReadMemoryByAddress(nHandle, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord):
    return _udsClient.udsReadMemoryByAddress(nHandle, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord)
udsReadMemoryByAddress = _udsClient.udsReadMemoryByAddress

def udsSecurityAccessRequestSeed(nHandle, securityAccessType, recordLength, seedDataRecord, actualLength):
    return _udsClient.udsSecurityAccessRequestSeed(nHandle, securityAccessType, recordLength, seedDataRecord, actualLength)
udsSecurityAccessRequestSeed = _udsClient.udsSecurityAccessRequestSeed

def udsSecurityAccessSendKey(nHandle, securityAccessType, recordLength, securityKey):
    return _udsClient.udsSecurityAccessSendKey(nHandle, securityAccessType, recordLength, securityKey)
udsSecurityAccessSendKey = _udsClient.udsSecurityAccessSendKey

def udsCommunicationControl(nHandle, controlType, communicationType, responseRequired):
    return _udsClient.udsCommunicationControl(nHandle, controlType, communicationType, responseRequired)
udsCommunicationControl = _udsClient.udsCommunicationControl

def udsWriteDataByIdentifier(nHandle, dataIdentifier, recordLength, dataRecord):
    return _udsClient.udsWriteDataByIdentifier(nHandle, dataIdentifier, recordLength, dataRecord)
udsWriteDataByIdentifier = _udsClient.udsWriteDataByIdentifier

def udsInputOutputControlByIdentifier(nHandle, dataIdentifier, controlType, controlLength, controlRecord, statusLength, statusRecord, actualLength):
    return _udsClient.udsInputOutputControlByIdentifier(nHandle, dataIdentifier, controlType, controlLength, controlRecord, statusLength, statusRecord, actualLength)
udsInputOutputControlByIdentifier = _udsClient.udsInputOutputControlByIdentifier

def udsRoutineControl(nHandle, routineControlType, routineIdentifier, inputDataLength, inputData, outputDataLength, outputData, actualLength):
    return _udsClient.udsRoutineControl(nHandle, routineControlType, routineIdentifier, inputDataLength, inputData, outputDataLength, outputData, actualLength)
udsRoutineControl = _udsClient.udsRoutineControl

def udsRequestDownload(nHandle, dataFormatIdentifier, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord, actualLength):
    return _udsClient.udsRequestDownload(nHandle, dataFormatIdentifier, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord, actualLength)
udsRequestDownload = _udsClient.udsRequestDownload

def udsRequestUpload(nHandle, dataFormatIdentifier, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord, actualLength):
    return _udsClient.udsRequestUpload(nHandle, dataFormatIdentifier, addressAndLengthFormatIdentifier, memoryAddress, memorySize, recordLength, dataRecord, actualLength)
udsRequestUpload = _udsClient.udsRequestUpload

def udsTransferData(nHandle, blockSequenceCounter, RequestLength, transferRequestParameterRecord, ResponseLength, transferResponseParameterRecord):
    return _udsClient.udsTransferData(nHandle, blockSequenceCounter, RequestLength, transferRequestParameterRecord, ResponseLength, transferResponseParameterRecord)
udsTransferData = _udsClient.udsTransferData

def udsRequestTransferExit(nHandle, RequestLength, transferRequestParameterRecord, ResponseLength, transferResponseParameterRecord):
    return _udsClient.udsRequestTransferExit(nHandle, RequestLength, transferRequestParameterRecord, ResponseLength, transferResponseParameterRecord)
udsRequestTransferExit = _udsClient.udsRequestTransferExit

def udsTesterPresent(nHandle, responseRequired):
    return _udsClient.udsTesterPresent(nHandle, responseRequired)
udsTesterPresent = _udsClient.udsTesterPresent

def udsWriteMemoryByAddress(nHandle, addressAndLengthFormatIdentifier, memoryAddress, memorySize, dataRecord):
    return _udsClient.udsWriteMemoryByAddress(nHandle, addressAndLengthFormatIdentifier, memoryAddress, memorySize, dataRecord)
udsWriteMemoryByAddress = _udsClient.udsWriteMemoryByAddress

def udsControlDTCSetting(nHandle, DTCSettingType, recordLength, DTCSettingControlOptionRecord, responseRequired):
    return _udsClient.udsControlDTCSetting(nHandle, DTCSettingType, recordLength, DTCSettingControlOptionRecord, responseRequired)
udsControlDTCSetting = _udsClient.udsControlDTCSetting
# This file is compatible with both classic and new-style classes.


