# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Shaggy', [dirname(__file__)])
        except ImportError:
            import _Shaggy
            return _Shaggy
        if fp is not None:
            try:
                _mod = imp.load_module('_Shaggy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Shaggy = swig_import_helper()
    del swig_import_helper
else:
    import _Shaggy
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Shaggy.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _Shaggy.SwigPyIterator_value(self)
    def incr(self, n=1): return _Shaggy.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _Shaggy.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _Shaggy.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _Shaggy.SwigPyIterator_equal(self, *args)
    def copy(self): return _Shaggy.SwigPyIterator_copy(self)
    def next(self): return _Shaggy.SwigPyIterator_next(self)
    def __next__(self): return _Shaggy.SwigPyIterator___next__(self)
    def previous(self): return _Shaggy.SwigPyIterator_previous(self)
    def advance(self, *args): return _Shaggy.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _Shaggy.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _Shaggy.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _Shaggy.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _Shaggy.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _Shaggy.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _Shaggy.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _Shaggy.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Error(Exception):
    def __init__(self, *args):
        Exception(args[1:])
        if len(args) >= 1 and type(args[0]) is str:
            self.myexc = error(args[0])
        else:
            self.myexc = error()
    @property
    def message(self):
        return self.myexc.message()
    def __str__(self):
        return 'Shaggy::Error: ' + self.myexc.message()

class error(_object):
    """Proxy of C++ shaggy::error class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, error, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, error, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> error
        __init__(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        this = _Shaggy.new_error(*args)
        try: self.this.append(this)
        except: self.this = this
    def has(self):
        """
        has(self) -> bool

        Parameters:
            self: shaggy::error *

        """
        return _Shaggy.error_has(self)

    def value(self):
        """
        value(self) -> int

        Parameters:
            self: shaggy::error *

        """
        return _Shaggy.error_value(self)

    def message(self):
        """
        message(self) -> std::string

        Parameters:
            self: shaggy::error *

        """
        return _Shaggy.error_message(self)

    __swig_destroy__ = _Shaggy.delete_error
    __del__ = lambda self : None;
error_swigregister = _Shaggy.error_swigregister
error_swigregister(error)

ADC = _Shaggy.ADC
CAN = _Shaggy.CAN
ANY = _Shaggy.ANY
ALL = _Shaggy.ALL
NONE = _Shaggy.NONE
class Shaggy(_object):
    """Proxy of C++ Shaggy class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Shaggy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Shaggy, name)
    __repr__ = _swig_repr
    def system(self):
        """
        system(self) -> System

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_system(self)

    def garage(self):
        """
        garage(self) -> Garage

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_garage(self)

    def jumpbox(self):
        """
        jumpbox(self) -> Jumpbox

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_jumpbox(self)

    def van(self, ip="10"):
        """
        van(self, ip="10") -> Van

        Parameters:
            ip: std::string

        van(self) -> Van

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_van(self, ip)

    def cid(self):
        """
        cid(self) -> CID

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_cid(self)

    def ic(self):
        """
        ic(self) -> IC

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_ic(self)

    def gw(self):
        """
        gw(self) -> GW

        Parameters:
            self: Shaggy *

        """
        return _Shaggy.Shaggy_gw(self)

    def __init__(self): 
        """__init__(self) -> Shaggy"""
        this = _Shaggy.new_Shaggy()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Shaggy.delete_Shaggy
    __del__ = lambda self : None;
Shaggy_swigregister = _Shaggy.Shaggy_swigregister
Shaggy_swigregister(Shaggy)

class System(_object):
    """Proxy of C++ System class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, System, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, System, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setLogfile(self, *args):
        """
        setLogfile(self, arg2)

        Parameters:
            arg2: std::string

        """
        return _Shaggy.System_setLogfile(self, *args)

    def closeLogfile(self):
        """
        closeLogfile(self)

        Parameters:
            self: System *

        """
        return _Shaggy.System_closeLogfile(self)

    def console(self, *args):
        """
        console(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.System_console(self, *args)

    def timestamp(self, *args):
        """
        timestamp(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.System_timestamp(self, *args)

    def log(self, *args):
        """
        log(self, arg2)

        Parameters:
            arg2: std::string

        """
        return _Shaggy.System_log(self, *args)

    def version(self):
        """
        version(self) -> std::string

        Parameters:
            self: System *

        """
        return _Shaggy.System_version(self)

    def exception(self, *args):
        """
        exception(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.System_exception(self, *args)

    def debugProtocols(self, *args):
        """
        debugProtocols(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.System_debugProtocols(self, *args)

    __swig_destroy__ = _Shaggy.delete_System
    __del__ = lambda self : None;
System_swigregister = _Shaggy.System_swigregister
System_swigregister(System)

class Garage(_object):
    """Proxy of C++ Garage class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Garage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Garage, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    QUERY = _Shaggy.Garage_QUERY
    DEV = _Shaggy.Garage_DEV
    PROD = _Shaggy.Garage_PROD
    def garage(self, *args):
        """
        garage(self, garage) -> enum Garage::Type

        Parameters:
            garage: enum enum Garage::Type

        """
        return _Shaggy.Garage_garage(self, *args)

    def tag(self):
        """
        tag(self) -> std::string

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_tag(self)

    def setid(self, *args):
        """
        setid(self, arg2, arg3)

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.Garage_setid(self, *args)

    def login(self, *args):
        """
        login(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.Garage_login(self, *args)

    def token(self):
        """
        token(self) -> std::string

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_token(self)

    def authenticated(self):
        """
        authenticated(self) -> bool

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_authenticated(self)

    def status(self):
        """
        status(self) -> error

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_status(self)

    def unlock(self, *args):
        """
        unlock(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_unlock(self, *args)

    def vitals(self, *args):
        """
        vitals(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_vitals(self, *args)

    def packages(self, *args):
        """
        packages(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_packages(self, *args)

    def package_id(self, *args):
        """
        package_id(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_package_id(self, *args)

    def viewPackageDiff(self, *args):
        """
        viewPackageDiff(self, source, target) -> error

        Parameters:
            source: std::string
            target: std::string

        """
        return _Shaggy.Garage_viewPackageDiff(self, *args)

    def createPackageDiff(self, *args):
        """
        createPackageDiff(self, source, target) -> error

        Parameters:
            source: std::string
            target: std::string

        """
        return _Shaggy.Garage_createPackageDiff(self, *args)

    def releases(self, *args):
        """
        releases(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_releases(self, *args)

    def permissions(self):
        """
        permissions(self) -> error

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_permissions(self)

    def vehicles(self, *args):
        """
        vehicles(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_vehicles(self, *args)

    def createJob(self, *args):
        """
        createJob(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_createJob(self, *args)

    def jobStatus(self, *args):
        """
        jobStatus(self, arg2, arg3) -> error

        Parameters:
            arg2: long long
            arg3: long long

        """
        return _Shaggy.Garage_jobStatus(self, *args)

    def activeJobs(self, *args):
        """
        activeJobs(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_activeJobs(self, *args)

    def inactiveJobs(self, *args):
        """
        inactiveJobs(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_inactiveJobs(self, *args)

    def cars(self):
        """
        cars(self) -> error

        Parameters:
            self: Garage *

        """
        return _Shaggy.Garage_cars(self)

    def uploadJob(self, *args):
        """
        uploadJob(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Garage_uploadJob(self, *args)

    def hammerJob(self, *args):
        """
        hammerJob(self, arg2) -> error

        Parameters:
            arg2: long long

        """
        return _Shaggy.Garage_hammerJob(self, *args)

    def abandonJob(self, *args):
        """
        abandonJob(self, arg2) -> error

        Parameters:
            arg2: long long

        """
        return _Shaggy.Garage_abandonJob(self, *args)

    __swig_destroy__ = _Shaggy.delete_Garage
    __del__ = lambda self : None;
Garage_swigregister = _Shaggy.Garage_swigregister
Garage_swigregister(Garage)

class Jumpbox(_object):
    """Proxy of C++ Jumpbox class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Jumpbox, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Jumpbox, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> Jumpbox"""
        this = _Shaggy.new_Jumpbox()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Shaggy.delete_Jumpbox
    __del__ = lambda self : None;
Jumpbox_swigregister = _Shaggy.Jumpbox_swigregister
Jumpbox_swigregister(Jumpbox)

MM_BUS_CAN_0 = _Shaggy.MM_BUS_CAN_0
MM_BUS_CAN_1 = _Shaggy.MM_BUS_CAN_1
MM_BUS_CAN_2 = _Shaggy.MM_BUS_CAN_2
MM_BUS_CAN_3 = _Shaggy.MM_BUS_CAN_3
MM_BUS_CAN_4 = _Shaggy.MM_BUS_CAN_4
MM_BUS_CAN_5 = _Shaggy.MM_BUS_CAN_5
MM_BUS_CAN_N = _Shaggy.MM_BUS_CAN_N
MM_BUS_LIN_0 = _Shaggy.MM_BUS_LIN_0
MM_BUS_LIN_1 = _Shaggy.MM_BUS_LIN_1
MM_BUS_LIN_2 = _Shaggy.MM_BUS_LIN_2
MM_BUS_LIN_3 = _Shaggy.MM_BUS_LIN_3
MM_BUS_LIN_N = _Shaggy.MM_BUS_LIN_N
MM_BUS_GPIO_1 = _Shaggy.MM_BUS_GPIO_1
MM_BUS_GPIO_2 = _Shaggy.MM_BUS_GPIO_2
MM_BUS_GPIO_3 = _Shaggy.MM_BUS_GPIO_3
MM_BUS_GPIO_4 = _Shaggy.MM_BUS_GPIO_4
MM_BUS_GPIO_N = _Shaggy.MM_BUS_GPIO_N
MM_CAN_BAUD_1M = _Shaggy.MM_CAN_BAUD_1M
MM_CAN_BAUD_500K = _Shaggy.MM_CAN_BAUD_500K
MM_CAN_BAUD_125K = _Shaggy.MM_CAN_BAUD_125K
MM_CAN_BAUD_83_3K = _Shaggy.MM_CAN_BAUD_83_3K
MM_CAN_BAUD_33_3K = _Shaggy.MM_CAN_BAUD_33_3K
MM_LIN_BAUD_9600 = _Shaggy.MM_LIN_BAUD_9600
MM_LIN_BAUD_19200 = _Shaggy.MM_LIN_BAUD_19200
MM_LIN_BAUD_10470 = _Shaggy.MM_LIN_BAUD_10470
MM_STREAM_BUS_0 = _Shaggy.MM_STREAM_BUS_0
MM_STREAM_BUS_1 = _Shaggy.MM_STREAM_BUS_1
MM_STREAM_BUS_2 = _Shaggy.MM_STREAM_BUS_2
MM_STREAM_BUS_3 = _Shaggy.MM_STREAM_BUS_3
MM_STREAM_BUS_4 = _Shaggy.MM_STREAM_BUS_4
MM_STREAM_BUS_5 = _Shaggy.MM_STREAM_BUS_5
MM_STREAM_CAN = _Shaggy.MM_STREAM_CAN
MM_STREAM_LIN = _Shaggy.MM_STREAM_LIN
MM_STREAM_QUERY = _Shaggy.MM_STREAM_QUERY
MM_STREAM_CAN_ALL = _Shaggy.MM_STREAM_CAN_ALL
MM_STREAM_LIN_ALL = _Shaggy.MM_STREAM_LIN_ALL
MM_STREAM_CAN_NONE = _Shaggy.MM_STREAM_CAN_NONE
MM_STREAM_LIN_NONE = _Shaggy.MM_STREAM_LIN_NONE
MM_CAPTURE_PROMISCUOUS = _Shaggy.MM_CAPTURE_PROMISCUOUS
class status(_object):
    """Proxy of C++ shaggy::van::status class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, status, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, status, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _Shaggy.delete_status
    __del__ = lambda self : None;
status_swigregister = _Shaggy.status_swigregister
status_swigregister(status)

class businfo(_object):
    """Proxy of C++ shaggy::van::businfo class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, businfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, businfo, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _Shaggy.delete_businfo
    __del__ = lambda self : None;
businfo_swigregister = _Shaggy.businfo_swigregister
businfo_swigregister(businfo)

class message(_object):
    """Proxy of C++ shaggy::van::message class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, message, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, message, name)
    __repr__ = _swig_repr
    def count(self):
        """
        count(self) -> int

        Parameters:
            self: shaggy::van::message *

        """
        return _Shaggy.message_count(self)

    def bus(self):
        """
        bus(self) -> uint8_t

        Parameters:
            self: shaggy::van::message *

        """
        return _Shaggy.message_bus(self)

    def id(self):
        """
        id(self) -> uint16_t

        Parameters:
            self: shaggy::van::message *

        """
        return _Shaggy.message_id(self)

    def name(self):
        """
        name(self) -> std::string

        Parameters:
            self: shaggy::van::message *

        """
        return _Shaggy.message_name(self)

    def signal(self, *args):
        """
        signal(self, arg2) -> std::string

        Parameters:
            arg2: int

        """
        return _Shaggy.message_signal(self, *args)

    def mask(self, *args):
        """
        mask(self, arg2) -> uint64_t

        Parameters:
            arg2: int

        """
        return _Shaggy.message_mask(self, *args)

    def __init__(self): 
        """__init__(self) -> message"""
        this = _Shaggy.new_message()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Shaggy.delete_message
    __del__ = lambda self : None;
message_swigregister = _Shaggy.message_swigregister
message_swigregister(message)

class vectorString(_object):
    """Proxy of C++ std::vector<(std::string)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorString, name)
    __repr__ = _swig_repr
    def iterator(self):
        """
        iterator(self) -> SwigPyIterator

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_iterator(self)

    def __iter__(self): return self.iterator()
    def __nonzero__(self):
        """
        __nonzero__(self) -> bool

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString___nonzero__(self)

    def __bool__(self):
        """
        __bool__(self) -> bool

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString___bool__(self)

    def __len__(self):
        """
        __len__(self) -> std::vector< std::string >::size_type

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString___len__(self)

    def pop(self):
        """
        pop(self) -> std::vector< std::string >::value_type

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_pop(self)

    def __getslice__(self, *args):
        """
        __getslice__(self, i, j) -> vectorString

        Parameters:
            i: std::vector< std::string >::difference_type
            j: std::vector< std::string >::difference_type

        """
        return _Shaggy.vectorString___getslice__(self, *args)

    def __setslice__(self, *args):
        """
        __setslice__(self, i, j, v=std::vector< std::string,std::allocator< std::string > >())

        Parameters:
            i: std::vector< std::string >::difference_type
            j: std::vector< std::string >::difference_type
            v: std::vector< std::string,std::allocator< std::string > > const &

        __setslice__(self, i, j)

        Parameters:
            i: std::vector< std::string >::difference_type
            j: std::vector< std::string >::difference_type

        """
        return _Shaggy.vectorString___setslice__(self, *args)

    def __delslice__(self, *args):
        """
        __delslice__(self, i, j)

        Parameters:
            i: std::vector< std::string >::difference_type
            j: std::vector< std::string >::difference_type

        """
        return _Shaggy.vectorString___delslice__(self, *args)

    def __delitem__(self, *args):
        """
        __delitem__(self, i)

        Parameters:
            i: std::vector< std::string >::difference_type

        __delitem__(self, slice)

        Parameters:
            slice: PySliceObject *

        """
        return _Shaggy.vectorString___delitem__(self, *args)

    def __getitem__(self, *args):
        """
        __getitem__(self, slice) -> vectorString

        Parameters:
            slice: PySliceObject *

        __getitem__(self, i) -> std::vector< std::string >::value_type const &

        Parameters:
            i: std::vector< std::string >::difference_type

        """
        return _Shaggy.vectorString___getitem__(self, *args)

    def __setitem__(self, *args):
        """
        __setitem__(self, slice, v)

        Parameters:
            slice: PySliceObject *
            v: std::vector< std::string,std::allocator< std::string > > const &

        __setitem__(self, slice)

        Parameters:
            slice: PySliceObject *

        __setitem__(self, i, x)

        Parameters:
            i: std::vector< std::string >::difference_type
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString___setitem__(self, *args)

    def append(self, *args):
        """
        append(self, x)

        Parameters:
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString_append(self, *args)

    def empty(self):
        """
        empty(self) -> bool

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_empty(self)

    def size(self):
        """
        size(self) -> std::vector< std::string >::size_type

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_size(self)

    def clear(self):
        """
        clear(self)

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_clear(self)

    def swap(self, *args):
        """
        swap(self, v)

        Parameters:
            v: std::vector< std::string > &

        """
        return _Shaggy.vectorString_swap(self, *args)

    def get_allocator(self):
        """
        get_allocator(self) -> std::vector< std::string >::allocator_type

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_get_allocator(self)

    def begin(self):
        """
        begin(self) -> std::vector< std::string >::iterator

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_begin(self)

    def end(self):
        """
        end(self) -> std::vector< std::string >::iterator

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_end(self)

    def rbegin(self):
        """
        rbegin(self) -> std::vector< std::string >::reverse_iterator

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_rbegin(self)

    def rend(self):
        """
        rend(self) -> std::vector< std::string >::reverse_iterator

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_rend(self)

    def pop_back(self):
        """
        pop_back(self)

        Parameters:
            self: std::vector< std::string > *

        """
        return _Shaggy.vectorString_pop_back(self)

    def erase(self, *args):
        """
        erase(self, pos) -> std::vector< std::string >::iterator

        Parameters:
            pos: std::vector< std::string >::iterator

        erase(self, first, last) -> std::vector< std::string >::iterator

        Parameters:
            first: std::vector< std::string >::iterator
            last: std::vector< std::string >::iterator

        """
        return _Shaggy.vectorString_erase(self, *args)

    def __init__(self, *args): 
        """
        __init__(self) -> vectorString
        __init__(self, arg2) -> vectorString

        Parameters:
            arg2: std::vector< std::string > const &

        __init__(self, size) -> vectorString

        Parameters:
            size: std::vector< std::string >::size_type

        __init__(self, size, value) -> vectorString

        Parameters:
            size: std::vector< std::string >::size_type
            value: std::vector< std::string >::value_type const &

        """
        this = _Shaggy.new_vectorString(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args):
        """
        push_back(self, x)

        Parameters:
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString_push_back(self, *args)

    def front(self):
        """
        front(self) -> std::vector< std::string >::value_type const &

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_front(self)

    def back(self):
        """
        back(self) -> std::vector< std::string >::value_type const &

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_back(self)

    def assign(self, *args):
        """
        assign(self, n, x)

        Parameters:
            n: std::vector< std::string >::size_type
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString_assign(self, *args)

    def resize(self, *args):
        """
        resize(self, new_size)

        Parameters:
            new_size: std::vector< std::string >::size_type

        resize(self, new_size, x)

        Parameters:
            new_size: std::vector< std::string >::size_type
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString_resize(self, *args)

    def insert(self, *args):
        """
        insert(self, pos, x) -> std::vector< std::string >::iterator

        Parameters:
            pos: std::vector< std::string >::iterator
            x: std::vector< std::string >::value_type const &

        insert(self, pos, n, x)

        Parameters:
            pos: std::vector< std::string >::iterator
            n: std::vector< std::string >::size_type
            x: std::vector< std::string >::value_type const &

        """
        return _Shaggy.vectorString_insert(self, *args)

    def reserve(self, *args):
        """
        reserve(self, n)

        Parameters:
            n: std::vector< std::string >::size_type

        """
        return _Shaggy.vectorString_reserve(self, *args)

    def capacity(self):
        """
        capacity(self) -> std::vector< std::string >::size_type

        Parameters:
            self: std::vector< std::string > const *

        """
        return _Shaggy.vectorString_capacity(self)

    __swig_destroy__ = _Shaggy.delete_vectorString
    __del__ = lambda self : None;
vectorString_swigregister = _Shaggy.vectorString_swigregister
vectorString_swigregister(vectorString)

class msg(_object):
    """Proxy of C++ shaggy::van::msg class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, msg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, msg, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, arg2, arg3, arg4, arg5, arg6) -> msg

        Parameters:
            arg2: uint8_t
            arg3: uint16_t
            arg4: uint8_t
            arg5: uint32_t
            arg6: uint64_t

        """
        this = _Shaggy.new_msg(*args)
        try: self.this.append(this)
        except: self.this = this
    def bus(self):
        """
        bus(self) -> uint8_t

        Parameters:
            self: shaggy::van::msg *

        """
        return _Shaggy.msg_bus(self)

    def id(self):
        """
        id(self) -> uint16_t

        Parameters:
            self: shaggy::van::msg *

        """
        return _Shaggy.msg_id(self)

    def len(self):
        """
        len(self) -> uint8_t

        Parameters:
            self: shaggy::van::msg *

        """
        return _Shaggy.msg_len(self)

    def time(self):
        """
        time(self) -> uint32_t

        Parameters:
            self: shaggy::van::msg *

        """
        return _Shaggy.msg_time(self)

    def data(self):
        """
        data(self) -> uint64_t

        Parameters:
            self: shaggy::van::msg *

        """
        return _Shaggy.msg_data(self)

    def __str__(self): return _Shaggy.msg___str__(self)
    __swig_destroy__ = _Shaggy.delete_msg
    __del__ = lambda self : None;
msg_swigregister = _Shaggy.msg_swigregister
msg_swigregister(msg)

class stream(_object):
    """Proxy of C++ shaggy::van::stream class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, stream, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, stream, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def write(self, *args):
        """
        write(self, arg2) -> error

        Parameters:
            arg2: std::vector< shaggy::van::msg,std::allocator< shaggy::van::msg > >

        """
        return _Shaggy.stream_write(self, *args)

    def read(self, timeout=500):
        """
        read(self, timeout=500) -> error

        Parameters:
            timeout: unsigned int

        read(self) -> error

        Parameters:
            self: shaggy::van::stream *

        """
        return _Shaggy.stream_read(self, timeout)

    def bus(self, *args):
        """
        bus(self, arg2) -> error

        Parameters:
            arg2: uint8_t

        """
        return _Shaggy.stream_bus(self, *args)

    def epoch(self):
        """
        epoch(self) -> error

        Parameters:
            self: shaggy::van::stream *

        """
        return _Shaggy.stream_epoch(self)

    __swig_destroy__ = _Shaggy.delete_stream
    __del__ = lambda self : None;
stream_swigregister = _Shaggy.stream_swigregister
stream_swigregister(stream)

class Van(_object):
    """Proxy of C++ Van class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Van, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Van, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def xfer(self):
        """
        xfer(self) -> Xfer

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_xfer(self)

    def connect(self):
        """
        connect(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_connect(self)

    def disconnect(self):
        """
        disconnect(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_disconnect(self)

    def ip(self):
        """
        ip(self) -> std::string

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_ip(self)

    def connected(self):
        """
        connected(self) -> bool

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_connected(self)

    def ping(self):
        """
        ping(self) -> bool

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_ping(self)

    def busmap(self, *args):
        """
        busmap(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: unsigned int

        """
        return _Shaggy.Van_busmap(self, *args)

    def busunmap(self, *args):
        """
        busunmap(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: unsigned int

        """
        return _Shaggy.Van_busunmap(self, *args)

    def version(self):
        """
        version(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_version(self)

    def reset(self, *args):
        """
        reset(self, arg2) -> error

        Parameters:
            arg2: unsigned short

        """
        return _Shaggy.Van_reset(self, *args)

    def dbc(self, *args):
        """
        dbc(self, dir) -> error

        Parameters:
            dir: std::string

        dbc(self, arg2) -> error

        Parameters:
            arg2: std::map< std::string,std::string >

        """
        return _Shaggy.Van_dbc(self, *args)

    def ldf(self, *args):
        """
        ldf(self, arg2) -> error

        Parameters:
            arg2: std::map< std::string,std::string >

        """
        return _Shaggy.Van_ldf(self, *args)

    def baud(self, *args):
        """
        baud(self, arg2, arg3) -> error

        Parameters:
            arg2: unsigned int
            arg3: unsigned int

        """
        return _Shaggy.Van_baud(self, *args)

    def send(self, *args):
        """
        send(self, arg2, arg3, arg4, arg5, arg6, arg7) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint8_t
            arg4: uint8_t
            arg5: uint16_t
            arg6: uint16_t
            arg7: uint64_t

        """
        return _Shaggy.Van_send(self, *args)

    def signal(self, *args):
        """
        signal(self, arg2, arg3, period=0xffff) -> error

        Parameters:
            arg2: std::string
            arg3: std::string
            period: uint16_t

        signal(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        signal(self, arg2) -> error

        Parameters:
            arg2: std::map< std::string,std::string >

        """
        return _Shaggy.Van_signal(self, *args)

    def process(self, *args):
        """
        process(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: std::string
            arg3: std::string
            arg4: unsigned int

        """
        return _Shaggy.Van_process(self, *args)

    def adc(self, *args):
        """
        adc(self, arg2, arg3, arg4, arg5) -> error

        Parameters:
            arg2: unsigned int
            arg3: unsigned int
            arg4: unsigned int
            arg5: unsigned int

        """
        return _Shaggy.Van_adc(self, *args)

    def read(self, *args):
        """
        read(self, arg2) -> error

        Parameters:
            arg2: std::string

        read(self, arg2, arg3, arg4, arg5) -> error

        Parameters:
            arg2: unsigned int
            arg3: unsigned int
            arg4: unsigned int
            arg5: unsigned int

        """
        return _Shaggy.Van_read(self, *args)

    def capture(self, *args):
        """
        capture(self, arg2, arg3) -> error

        Parameters:
            arg2: std::vector< std::string,std::allocator< std::string > > const &
            arg3: bool

        capture(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: bool

        """
        return _Shaggy.Van_capture(self, *args)

    def poll(self, *args):
        """
        poll(self, arg2) -> error

        Parameters:
            arg2: shaggy::van::key &

        """
        return _Shaggy.Van_poll(self, *args)

    def flush(self):
        """
        flush(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_flush(self)

    def reactivate(self, *args):
        """
        reactivate(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.Van_reactivate(self, *args)

    def uptime(self):
        """
        uptime(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_uptime(self)

    def status(self):
        """
        status(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_status(self)

    def businfo(self):
        """
        businfo(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_businfo(self)

    def message(self, *args):
        """
        message(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Van_message(self, *args)

    def lin_unpack(self, *args):
        """
        lin_unpack(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint16_t
            arg4: uint64_t

        lin_unpack(self, arg2, arg3, arg4, arg5, arg7) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint16_t
            arg4: uint64_t
            arg5: uint64_t
            arg7: uint64_t

        """
        return _Shaggy.Van_lin_unpack(self, *args)

    def lin_resolve(self, *args):
        """
        lin_resolve(self, arg2, arg3, arg4, arg5) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint16_t
            arg4: uint64_t
            arg5: uint64_t

        """
        return _Shaggy.Van_lin_resolve(self, *args)

    def flash(self, *args):
        """
        flash(self, arg2, arg3, timeout=5000) -> error

        Parameters:
            arg2: uint8_t
            arg3: std::string
            timeout: uint32_t

        flash(self, arg2, arg3) -> error

        Parameters:
            arg2: uint8_t
            arg3: std::string

        """
        return _Shaggy.Van_flash(self, *args)

    def vdebug(self, *args):
        """
        vdebug(self, arg2) -> error

        Parameters:
            arg2: uint16_t

        """
        return _Shaggy.Van_vdebug(self, *args)

    def stream(self):
        """
        stream(self) -> error

        Parameters:
            self: Van *

        """
        return _Shaggy.Van_stream(self)

    __swig_destroy__ = _Shaggy.delete_Van
    __del__ = lambda self : None;
Van_swigregister = _Shaggy.Van_swigregister
Van_swigregister(Van)

class UDS(_object):
    """Proxy of C++ UDS class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UDS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UDS, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _Shaggy.delete_UDS
    __del__ = lambda self : None;
UDS_swigregister = _Shaggy.UDS_swigregister
UDS_swigregister(UDS)

class CID(_object):
    """Proxy of C++ CID class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CID, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CID, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def GetCID():
        """GetCID() -> CID"""
        return _Shaggy.CID_GetCID()

    if _newclass:GetCID = staticmethod(GetCID)
    __swig_getmethods__["GetCID"] = lambda x: GetCID
    def ssh(self):
        """
        ssh(self) -> SSH

        Parameters:
            self: CID *

        """
        return _Shaggy.CID_ssh(self)

    __swig_destroy__ = _Shaggy.delete_CID
    __del__ = lambda self : None;
CID_swigregister = _Shaggy.CID_swigregister
CID_swigregister(CID)

def CID_GetCID():
  """CID_GetCID() -> CID"""
  return _Shaggy.CID_GetCID()

class IC(_object):
    """Proxy of C++ IC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IC, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def GetIC():
        """GetIC() -> IC"""
        return _Shaggy.IC_GetIC()

    if _newclass:GetIC = staticmethod(GetIC)
    __swig_getmethods__["GetIC"] = lambda x: GetIC
    def ssh(self):
        """
        ssh(self) -> SSH

        Parameters:
            self: IC *

        """
        return _Shaggy.IC_ssh(self)

    __swig_destroy__ = _Shaggy.delete_IC
    __del__ = lambda self : None;
IC_swigregister = _Shaggy.IC_swigregister
IC_swigregister(IC)

def IC_GetIC():
  """IC_GetIC() -> IC"""
  return _Shaggy.IC_GetIC()

class GW(_object):
    """Proxy of C++ GW class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GW, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GW, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def isopen(self):
        """
        isopen(self) -> bool

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_isopen(self)

    def lube(self, *args):
        """
        lube(self) -> error
        lube(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.GW_lube(self, *args)

    def unlube(self):
        """
        unlube(self)

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_unlube(self)

    def VIN(self):
        """
        VIN(self) -> std::string

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_VIN(self)

    def suppressKey(self, *args):
        """
        suppressKey(self, arg2)

        Parameters:
            arg2: bool

        """
        return _Shaggy.GW_suppressKey(self, *args)

    def xfer(self):
        """
        xfer(self) -> Xfer

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_xfer(self)

    def diag_reboot(self):
        """
        diag_reboot(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_reboot(self)

    def diag_app_version(self):
        """
        diag_app_version(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_app_version(self)

    def diag_app_crc_and_type(self):
        """
        diag_app_crc_and_type(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_app_crc_and_type(self)

    def diag_human_version(self):
        """
        diag_human_version(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_human_version(self)

    def diag_git_hash(self):
        """
        diag_git_hash(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_git_hash(self)

    def diag_monitor_can(self, *args):
        """
        diag_monitor_can(self, arg2, arg3, arg4, arg5) -> error

        Parameters:
            arg2: uint8_t
            arg3: bool
            arg4: uint16_t
            arg5: uint16_t

        """
        return _Shaggy.GW_diag_monitor_can(self, *args)

    def diag_inject_can(self, *args):
        """
        diag_inject_can(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint16_t
            arg4: uint64_t

        """
        return _Shaggy.GW_diag_inject_can(self, *args)

    def diag_bl_version(self):
        """
        diag_bl_version(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_bl_version(self)

    def diag_reboot_for_update(self, *args):
        """
        diag_reboot_for_update(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.GW_diag_reboot_for_update(self, *args)

    def diag_reset_tegra(self, *args):
        """
        diag_reset_tegra(self, arg2) -> error

        Parameters:
            arg2: bool

        """
        return _Shaggy.GW_diag_reset_tegra(self, *args)

    def diag_updater_sleep_delay(self, *args):
        """
        diag_updater_sleep_delay(self, arg2) -> error

        Parameters:
            arg2: uint8_t

        """
        return _Shaggy.GW_diag_updater_sleep_delay(self, *args)

    def diag_slow_vip_405hs(self, *args):
        """
        diag_slow_vip_405hs(self, arg2) -> error

        Parameters:
            arg2: bool

        """
        return _Shaggy.GW_diag_slow_vip_405hs(self, *args)

    def diag_set_debug_param(self, *args):
        """
        diag_set_debug_param(self, arg2, arg3) -> error

        Parameters:
            arg2: uint8_t
            arg3: uint32_t

        """
        return _Shaggy.GW_diag_set_debug_param(self, *args)

    def diag_get_debug_param(self, *args):
        """
        diag_get_debug_param(self, arg2) -> error

        Parameters:
            arg2: uint8_t

        """
        return _Shaggy.GW_diag_get_debug_param(self, *args)

    def diag_clear_log(self):
        """
        diag_clear_log(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_clear_log(self)

    def diag_cluster_power(self, *args):
        """
        diag_cluster_power(self, arg2) -> error

        Parameters:
            arg2: bool

        """
        return _Shaggy.GW_diag_cluster_power(self, *args)

    def diag_enable_shell(self):
        """
        diag_enable_shell(self) -> error

        Parameters:
            self: GW *

        """
        return _Shaggy.GW_diag_enable_shell(self)

    def diag_mcu_power(self, *args):
        """
        diag_mcu_power(self, arg2, arg3) -> error

        Parameters:
            arg2: uint8_t
            arg3: bool

        """
        return _Shaggy.GW_diag_mcu_power(self, *args)

    def diag_file_crc(self, *args):
        """
        diag_file_crc(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.GW_diag_file_crc(self, *args)

    def diag_hwidacq(self, *args):
        """
        diag_hwidacq(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.GW_diag_hwidacq(self, *args)

    def diag_drive_rail(self, *args):
        """
        diag_drive_rail(self, arg2) -> error

        Parameters:
            arg2: bool

        """
        return _Shaggy.GW_diag_drive_rail(self, *args)

    __swig_destroy__ = _Shaggy.delete_GW
    __del__ = lambda self : None;
GW_swigregister = _Shaggy.GW_swigregister
GW_swigregister(GW)

class channel(_object):
    """Proxy of C++ shaggy::channel class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, channel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, channel, name)
    __repr__ = _swig_repr
    def gets(self):
        """
        gets(self) -> error

        Parameters:
            self: shaggy::channel *

        """
        return _Shaggy.channel_gets(self)

    def puts(self, *args):
        """
        puts(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.channel_puts(self, *args)

    def eof(self):
        """
        eof(self) -> bool

        Parameters:
            self: shaggy::channel *

        """
        return _Shaggy.channel_eof(self)

    def close(self):
        """
        close(self) -> int

        Parameters:
            self: shaggy::channel *

        """
        return _Shaggy.channel_close(self)

    def __init__(self): 
        """__init__(self) -> channel"""
        this = _Shaggy.new_channel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Shaggy.delete_channel
    __del__ = lambda self : None;
channel_swigregister = _Shaggy.channel_swigregister
channel_swigregister(channel)

class SSH(_object):
    """Proxy of C++ SSH class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SSH, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SSH, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def init(self, *args):
        """
        init(self) -> error
        init(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.SSH_init(self, *args)

    def open(self):
        """
        open(self) -> bool

        Parameters:
            self: SSH *

        """
        return _Shaggy.SSH_open(self)

    def end(self):
        """
        end(self) -> error

        Parameters:
            self: SSH *

        """
        return _Shaggy.SSH_end(self)

    def run(self, *args):
        """
        run(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.SSH_run(self, *args)

    def send(self, *args):
        """
        send(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.SSH_send(self, *args)

    def sendbuf(self, *args):
        """
        sendbuf(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.SSH_sendbuf(self, *args)

    def recv(self, *args):
        """
        recv(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.SSH_recv(self, *args)

    def recvbuf(self, *args):
        """
        recvbuf(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.SSH_recvbuf(self, *args)

    def stream(self, *args):
        """
        stream(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.SSH_stream(self, *args)

    __swig_destroy__ = _Shaggy.delete_SSH
    __del__ = lambda self : None;
SSH_swigregister = _Shaggy.SSH_swigregister
SSH_swigregister(SSH)

class Xfer(_object):
    """Proxy of C++ Xfer class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Xfer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Xfer, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def read(self, *args):
        """
        read(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Xfer_read(self, *args)

    def write(self, *args):
        """
        write(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: std::string
            arg3: unsigned int
            arg4: std::string

        """
        return _Shaggy.Xfer_write(self, *args)

    def rename(self, *args):
        """
        rename(self, arg2, arg3) -> error

        Parameters:
            arg2: std::string
            arg3: std::string

        """
        return _Shaggy.Xfer_rename(self, *args)

    def offset(self, *args):
        """
        offset(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: std::string
            arg3: unsigned int
            arg4: unsigned int

        """
        return _Shaggy.Xfer_offset(self, *args)

    def mkdir(self, *args):
        """
        mkdir(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Xfer_mkdir(self, *args)

    def remove(self, *args):
        """
        remove(self, arg2) -> error

        Parameters:
            arg2: std::string

        """
        return _Shaggy.Xfer_remove(self, *args)

    def append(self, *args):
        """
        append(self, arg2, arg3, arg4) -> error

        Parameters:
            arg2: std::string
            arg3: unsigned int
            arg4: std::string

        """
        return _Shaggy.Xfer_append(self, *args)

    __swig_destroy__ = _Shaggy.delete_Xfer
    __del__ = lambda self : None;
Xfer_swigregister = _Shaggy.Xfer_swigregister
Xfer_swigregister(Xfer)

# This file is compatible with both classic and new-style classes.


