"""
version.py
Created on Jun 27, 2016

@author: tbell

@description: VersionLen and VersionOff are the definition and container for 
              known Tesla UDS Version data.
              This information is somewhat duplicated in the nodes.json. 
	      nodes.json is the source of truth, this file must match. It 
	      provides an easy/separate interface for development.

"""
from enum import IntEnum


class VersionLen(IntEnum):
    UNKNOWN_LEN = -1
    TESLA_CRC_LEN = 4
    TESLA_INFOMSG_VERSION_LEN = 3
    TESLA_INFOMSG_APP_CRC_LEN = TESLA_CRC_LEN
    TESLA_INFOMSG_BOOT_CRC_LEN = TESLA_CRC_LEN
    TESLA_INFOMSG_VAR_CRC_LEN = 4
    TESLA_INFOMSG_SUBCOMP1_VER_LEN_CRC = TESLA_CRC_LEN
    TESLA_INFOMSG_SUBCOMP2_VER_LEN_CRC = TESLA_CRC_LEN
    TESLA_INFOMSG_SUBCOMP3_VER_LEN_CRC = TESLA_CRC_LEN
    CRC_LEN = 4
    UDS_TESLA_DID_CRC_OUTPUT_LEN = CRC_LEN
    UDS_TESLA_DID_APP_CRC_LENGTH = CRC_LEN
    UDS_TESLA_DID_VARIANT_LENGTH = CRC_LEN
    UDS_TESLA_DID_BOOTCRC_LENGTH = CRC_LEN
    UDS_VALEO_SCCM_CRC_LEN = 0x0004
    TESLA_VERS_LEN = 3
    TESLA_VERSION_LEN = TESLA_VERS_LEN
    HND_VERSION_LEN = TESLA_VERS_LEN - 1
    UDS_BOSCH_ESP_DID_APP_SOFTWARE_VERSION_LENGTH = 8
    ESP_VERSION_LEN = UDS_BOSCH_ESP_DID_APP_SOFTWARE_VERSION_LENGTH
    ESPCAL_VERSION_LEN = UDS_TESLA_DID_VARIANT_LENGTH
    UDS_BOSCH_PARK_DID_APP_SOFTWARE_VERSION_LENGTH = 3
    PARK_VERSION_LEN = UDS_BOSCH_PARK_DID_APP_SOFTWARE_VERSION_LENGTH
    UDS_BITRON_MSM_RC_APP_SOFTWARE_VERSION_OUTPUT_LENGTH = 2
    MSM_VERSION_LEN = UDS_BITRON_MSM_RC_APP_SOFTWARE_VERSION_OUTPUT_LENGTH
    PTC_VERSION_LEN = 1
    PTCR_VERSION_LEN = 1
    RCCM_VERSION_LEN = 1
    CMP_VERSION_LEN = 3
    UDS_CONTI_EAS_DID_SW_VERSION_OUTPUT_LENGTH = 5
    EAS_VERSION_LEN = UDS_CONTI_EAS_DID_SW_VERSION_OUTPUT_LENGTH
    UDS_PANASONIC_ALL_DID_UNIT_VERSION_INFO_APP_LENGTH = 1
    TUNER_VERSION_LEN = UDS_PANASONIC_ALL_DID_UNIT_VERSION_INFO_APP_LENGTH
    UDS_DELPHI_OCS_CUSTOM_SI_VERSION_LENGTH = 2
    OCS_VERSION_LEN = UDS_DELPHI_OCS_CUSTOM_SI_VERSION_LENGTH
    UDS_DELPHI_SDM_DID_SW_VERSION_OUTPUT_LENGTH = 9
    SDM_VERSION_LEN = UDS_DELPHI_SDM_DID_SW_VERSION_OUTPUT_LENGTH
    UDS_DELPHI_SDM_DID_VERSION_LENGTH = 3
    SDM_APP_CAL_VERSION_LEN = UDS_DELPHI_SDM_DID_VERSION_LENGTH * 2
    UDS_VALEO_SCCM_DID_SW_VERSION_OUTPUT_LENGTH = 3
    SCCM_VERSION_LEN = UDS_VALEO_SCCM_DID_SW_VERSION_OUTPUT_LENGTH

    UDS_JLR_EPAS_DID_APP_SOFTWARE_VERSION_LENGTH = -1


class VersionOff(IntEnum):
    UNKNOWN_OFF = 0
    UDS_TESLA_DID_APP_CRC_OFFSET = 0
    UDS_TESLA_DID_BOOTCRC_OFFSET = 0
    TESLA_INFOMSG_VERSION_OFF = 2
    TESLA_INFOMSG_APP_CRC_OFF = 4
    TESLA_INFOMSG_BOOT_CRC_OFF = 4
    TESLA_INFOMSG_VAR_CRC_OFF = 4
    TESLA_VERS_OFF = 4
    TESLA_VERSION_OFF = TESLA_VERS_OFF
    TESLA_DDM_PDM_HND_VERSION_MSG_HWID_OFFSET = 1
    TESLA_DDM_PDM_HND_VERSION_OFF = TESLA_DDM_PDM_HND_VERSION_MSG_HWID_OFFSET + 1
    UDS_BOSCH_ESP_DID_APP_SOFTWARE_VERSION_OFFSET = 5
    ESP_VERSION_OFF = UDS_BOSCH_ESP_DID_APP_SOFTWARE_VERSION_OFFSET
    UDS_TESLA_DID_VARIANT_OFFSET = 0
    ESPCAL_VERSION_OFF = UDS_TESLA_DID_VARIANT_OFFSET
    UDS_BOSCH_PARK_DID_APP_SOFTWARE_VERSION_OFFSET = 0
    PARK_VERSION_OFF = UDS_BOSCH_PARK_DID_APP_SOFTWARE_VERSION_OFFSET
    UDS_BITRON_MSM_RC_APP_SOFTWARE_VERSION_OFFSET = 0
    MSM_VERSION_OFF = UDS_BITRON_MSM_RC_APP_SOFTWARE_VERSION_OFFSET
    PTC_VERSION_OFF = 7
    PTCR_VERSION_OFF = 7,
    RCCM_VERSION_OFF = 0
    CMP_VERSION_OFF = 0
    EAS_VERSION_OFF = 0
    UDS_PANASONIC_ALL_DID_UNIT_VERSION_INFO_APP_OFFSET = 3
    TUNER_VERSION_OFF = UDS_PANASONIC_ALL_DID_UNIT_VERSION_INFO_APP_OFFSET
    UDS_DELPHI_OCS_CUSTOM_SI_VERSION_OFFSET = 0
    OCS_VERSION_OFF = UDS_DELPHI_OCS_CUSTOM_SI_VERSION_OFFSET
    UDS_DELPHI_SDM_DID_APP_SW_VERSION_OFFSET = 0
    SDM_VERSION_OFF = UDS_DELPHI_SDM_DID_APP_SW_VERSION_OFFSET
    UDS_DELPHI_SDM_DID_CAL_SW_VERSION_OFFSET = 3
    SDM_CAL_VERSION_OFF = UDS_DELPHI_SDM_DID_CAL_SW_VERSION_OFFSET
    UDS_DELPHI_SDM_DID_BOOT_SW_VERSION_OFFSET = 6
    SDM_BOOT_VERSION_OFF = UDS_DELPHI_SDM_DID_BOOT_SW_VERSION_OFFSET
    SCCM_VERSION_OFF = 0
